// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.font;
import haxe.extern.Rest;
import love.filesystem.FileData;
import love.image.ImageData;
import lua.Table;
import lua.UserData;

/**
 * Allows you to work with fonts.
 */
@:native('love.font')
extern class Font {

	/**
	 * Creates a new BMFont Rasterizer.
	 * @param imageData The image data containing the drawable pictures of font glyphs.
	 * @param glyphs The sequence of glyphs in the ImageData.
	 * @param dpiscale DPI scale.
	 * @return The rasterizer.
	 */
	@:overload(function (fileName: String, glyphs: String, ?dpiscale: Float): Rasterizer {})
	public static function newBMFontRasterizer(imageData: ImageData, glyphs: String, ?dpiscale: Float): Rasterizer;

	/**
	 * Creates a new GlyphData.
	 * @param rasterizer The Rasterizer containing the font.
	 * @param glyph The character code of the glyph.
	 */
	public static function newGlyphData(rasterizer: Rasterizer, glyph: Float): Void;

	/**
	 * Creates a new Image Rasterizer.
	 * @param imageData Font image data.
	 * @param glyphs String containing font glyphs.
	 * @param extraSpacing Font extra spacing.
	 * @param dpiscale Font DPI scale.
	 * @return The rasterizer.
	 */
	public static function newImageRasterizer(imageData: ImageData, glyphs: String, ?extraSpacing: Float, ?dpiscale: Float): Rasterizer;

	/**
	 * Creates a new Rasterizer.
	 * @param filename The font file.
	 * @return The rasterizer.
	 */
	@:overload(function (data: FileData): Rasterizer {})
	@:overload(function (?size: Float, ?hinting: HintingMode, ?dpiscale: Float): Rasterizer {})
	@:overload(function (fileName: String, ?size: Float, ?hinting: HintingMode, ?dpiscale: Float): Rasterizer {})
	@:overload(function (fileData: FileData, ?size: Float, ?hinting: HintingMode, ?dpiscale: Float): Rasterizer {})
	@:overload(function (imageData: ImageData, glyphs: String, ?dpiscale: Float): Rasterizer {})
	@:overload(function (fileName: String, glyphs: String, ?dpiscale: Float): Rasterizer {})
	public static function newRasterizer(filename: String): Rasterizer;

	/**
	 * Creates a new TrueType Rasterizer.
	 * @param size The font size.
	 * @param hinting True Type hinting mode.
	 * @param dpiscale The font DPI scale.
	 * @return The rasterizer.
	 */
	@:overload(function (fileName: String, ?size: Float, ?hinting: HintingMode, ?dpiscale: Float): Rasterizer {})
	@:overload(function (fileData: FileData, ?size: Float, ?hinting: HintingMode, ?dpiscale: Float): Rasterizer {})
	public static function newTrueTypeRasterizer(?size: Float, ?hinting: HintingMode, ?dpiscale: Float): Rasterizer;
}