// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.font;
import haxe.extern.Rest;
import love.image.PixelFormat;
import lua.Table;
import lua.UserData;

/**
 * A GlyphData represents a drawable symbol of a font Rasterizer.
 */
extern class GlyphData extends Data {

	/**
	 * Gets glyph advance.
	 * @return Glyph advance.
	 */
	public function getAdvance(): Float;

	/**
	 * Gets glyph bearing.
	 */
	public function getBearing(): GlyphDataGetBearingResult;

	/**
	 * Gets glyph bounding box.
	 */
	public function getBoundingBox(): GlyphDataGetBoundingBoxResult;

	/**
	 * Gets glyph dimensions.
	 */
	public function getDimensions(): GlyphDataGetDimensionsResult;

	/**
	 * Gets glyph pixel format.
	 * @return Glyph pixel format.
	 */
	public function getFormat(): PixelFormat;

	/**
	 * Gets glyph number.
	 * @return Glyph number.
	 */
	public function getGlyph(): Float;

	/**
	 * Gets glyph string.
	 * @return Glyph string.
	 */
	public function getGlyphString(): String;

	/**
	 * Gets glyph height.
	 * @return Glyph height.
	 */
	public function getHeight(): Float;

	/**
	 * Gets glyph width.
	 * @return Glyph width.
	 */
	public function getWidth(): Float;
}

@:multiReturn
extern class GlyphDataGetDimensionsResult {
	var width: Float;
	var height: Float;
}

@:multiReturn
extern class GlyphDataGetBoundingBoxResult {
	var x: Float;
	var y: Float;
	var width: Float;
	var height: Float;
}

@:multiReturn
extern class GlyphDataGetBearingResult {
	var bx: Float;
	var by: Float;
}