// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.font;

/**
 * True Type hinting mode.
 */
enum abstract HintingMode (String) from String to String {

	/**
	 * Default hinting. Should be preferred for typical antialiased fonts.
	 */
	var Normal = 'normal';

	/**
	 * Results in fuzzier text but can sometimes preserve the original glyph shapes of the text better than normal hinting.
	 */
	var Light = 'light';

	/**
	 * Results in aliased / unsmoothed text with either full opacity or completely transparent pixels. Should be used when antialiasing is not desired for the font.
	 */
	var Mono = 'mono';

	/**
	 * Disables hinting for the font. Results in fuzzier text.
	 */
	var None = 'none';
}