// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.font;
import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

/**
 * A Rasterizer handles font rendering, containing the font data (image or TrueType font) and drawable glyphs.
 */
extern class Rasterizer extends Object {

	/**
	 * Gets font advance.
	 * @return Font advance.
	 */
	public function getAdvance(): Float;

	/**
	 * Gets ascent height.
	 * @return Ascent height.
	 */
	public function getAscent(): Float;

	/**
	 * Gets descent height.
	 * @return Descent height.
	 */
	public function getDescent(): Float;

	/**
	 * Gets number of glyphs in font.
	 * @return Glyphs count.
	 */
	public function getGlyphCount(): Float;

	/**
	 * Gets glyph data of a specified glyph.
	 * @param glyph Glyph
	 * @return Glyph data
	 */
	@:overload(function (glyphNumber: Float): GlyphData {})
	public function getGlyphData(glyph: String): GlyphData;

	/**
	 * Gets font height.
	 * @return Font height
	 */
	public function getHeight(): Float;

	/**
	 * Gets line height of a font.
	 * @return Line height of a font.
	 */
	public function getLineHeight(): Float;

	/**
	 * Checks if font contains specified glyphs.
	 * @param glyph1 Glyph
	 * @param ... Additional glyphs
	 * @return Whatever font contains specified glyphs.
	 */
	public function hasGlyphs(glyph1: Dynamic, args: Rest<Dynamic>): Bool;
}