// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.audio;

/**
 * The different distance models.
 * Extended information can be found in the chapter "3.4. Attenuation By Distance" of the OpenAL 1.1 specification.
 */
enum abstract DistanceModel (String) from String to String {

	/**
	 * Sources do not get attenuated.
	 */
	var None = 'none';

	/**
	 * Inverse distance attenuation.
	 */
	var Inverse = 'inverse';

	/**
	 * Inverse distance attenuation. Gain is clamped. In version 0.9.2 and older this is named '''inverse clamped'''.
	 */
	var Inverseclamped = 'inverseclamped';

	/**
	 * Linear attenuation.
	 */
	var Linear = 'linear';

	/**
	 * Linear attenuation. Gain is clamped. In version 0.9.2 and older this is named '''linear clamped'''.
	 */
	var Linearclamped = 'linearclamped';

	/**
	 * Exponential attenuation.
	 */
	var Exponent = 'exponent';

	/**
	 * Exponential attenuation. Gain is clamped. In version 0.9.2 and older this is named '''exponent clamped'''.
	 */
	var Exponentclamped = 'exponentclamped';
}