// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.audio;

/**
 * The different types of effects supported by love.audio.setEffect.
 */
enum abstract EffectType (String) from String to String {

	/**
	 * Plays multiple copies of the sound with slight pitch and time variation. Used to make sounds sound "fuller" or "thicker".
	 */
	var Chorus = 'chorus';

	/**
	 * Decreases the dynamic range of the sound, making the loud and quiet parts closer in volume, producing a more uniform amplitude throughout time.
	 */
	var Compressor = 'compressor';

	/**
	 * Alters the sound by amplifying it until it clips, shearing off parts of the signal, leading to a compressed and distorted sound.
	 */
	var Distortion = 'distortion';

	/**
	 * Decaying feedback based effect, on the order of seconds. Also known as delay; causes the sound to repeat at regular intervals at a decreasing volume.
	 */
	var Echo = 'echo';

	/**
	 * Adjust the frequency components of the sound using a 4-band (low-shelf, two band-pass and a high-shelf) equalizer.
	 */
	var Equalizer = 'equalizer';

	/**
	 * Plays two copies of the sound; while varying the phase, or equivalently delaying one of them, by amounts on the order of milliseconds, resulting in phasing sounds.
	 */
	var Flanger = 'flanger';

	/**
	 * Decaying feedback based effect, on the order of milliseconds. Used to simulate the reflection off of the surroundings.
	 */
	var Reverb = 'reverb';

	/**
	 * An implementation of amplitude modulation; multiplies the source signal with a simple waveform, to produce either volume changes, or inharmonic overtones.
	 */
	var Ringmodulator = 'ringmodulator';
}