// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.audio;

/**
 * The different types of waveforms that can be used with the '''ringmodulator''' EffectType.
 */
enum abstract EffectWaveform (String) {

	/**
	 * A sawtooth wave, also known as a ramp wave. Named for its linear rise, and (near-)instantaneous fall along time.
	 */
	var Sawtooth = 'sawtooth';

	/**
	 * A sine wave. Follows a trigonometric sine function.
	 */
	var Sine = 'sine';

	/**
	 * A square wave. Switches between high and low states (near-)instantaneously.
	 */
	var Square = 'square';

	/**
	 * A triangle wave. Follows a linear rise and fall that repeats periodically.
	 */
	var Triangle = 'triangle';
}