// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.audio;

/**
 * Types of filters for Sources.
 */
enum abstract FilterType (String) {

	/**
	 * Low-pass filter. High frequency sounds are attenuated.
	 */
	var Lowpass = 'lowpass';

	/**
	 * High-pass filter. Low frequency sounds are attenuated.
	 */
	var Highpass = 'highpass';

	/**
	 * Band-pass filter. Both high and low frequency sounds are attenuated based on the given parameters.
	 */
	var Bandpass = 'bandpass';
}