// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.audio;

/**
 * Types of audio sources.
 * A good rule of thumb is to use stream for music files and static for all short sound effects. Basically, you want to avoid loading large files into memory at once.
 */
enum abstract SourceType (String) {

	/**
	 * The whole audio is decoded.
	 */
	var Static = 'static';

	/**
	 * The audio is decoded in chunks when needed.
	 */
	var Stream = 'stream';

	/**
	 * The audio must be manually queued by the user.
	 */
	var Queue = 'queue';
}