// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.audio;

/**
 * Units that represent time.
 */
enum abstract TimeUnit (String) {

	/**
	 * Regular seconds.
	 */
	var Seconds = 'seconds';

	/**
	 * Audio samples.
	 */
	var Samples = 'samples';
}