// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.thread;
import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

/**
 * A Thread is a chunk of code that can run in parallel with other threads. Data can be sent between different threads with Channel objects.
 */
extern class Thread extends Object {

	/**
	 * Retrieves the error string from the thread if it produced an error.
	 * @return The error message, or nil if the Thread has not caused an error.
	 */
	public function getError(): String;

	/**
	 * Returns whether the thread is currently running.
	 * Threads which are not running can be (re)started with Thread:start.
	 * @return True if the thread is running, false otherwise.
	 */
	public function isRunning(): Bool;

	/**
	 * Starts the thread.
	 * Beginning with version 0.9.0, threads can be restarted after they have completed their execution.
	 */
	@:overload(function (args: Rest<Dynamic>): Void {})
	public function start(): Void;

	/**
	 * Wait for a thread to finish.
	 * This call will block until the thread finishes.
	 */
	public function wait(): Void;
}