// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.keyboard;

/**
 * All the keys you can press. Note that some keys may not be available on your keyboard or system.
 */
enum abstract KeyConstant (String) {

	/**
	 * The A key
	 */
	var A = 'a';

	/**
	 * The B key
	 */
	var B = 'b';

	/**
	 * The C key
	 */
	var C = 'c';

	/**
	 * The D key
	 */
	var D = 'd';

	/**
	 * The E key
	 */
	var E = 'e';

	/**
	 * The F key
	 */
	var F = 'f';

	/**
	 * The G key
	 */
	var G = 'g';

	/**
	 * The H key
	 */
	var H = 'h';

	/**
	 * The I key
	 */
	var I = 'i';

	/**
	 * The J key
	 */
	var J = 'j';

	/**
	 * The K key
	 */
	var K = 'k';

	/**
	 * The L key
	 */
	var L = 'l';

	/**
	 * The M key
	 */
	var M = 'm';

	/**
	 * The N key
	 */
	var N = 'n';

	/**
	 * The O key
	 */
	var O = 'o';

	/**
	 * The P key
	 */
	var P = 'p';

	/**
	 * The Q key
	 */
	var Q = 'q';

	/**
	 * The R key
	 */
	var R = 'r';

	/**
	 * The S key
	 */
	var S = 's';

	/**
	 * The T key
	 */
	var T = 't';

	/**
	 * The U key
	 */
	var U = 'u';

	/**
	 * The V key
	 */
	var V = 'v';

	/**
	 * The W key
	 */
	var W = 'w';

	/**
	 * The X key
	 */
	var X = 'x';

	/**
	 * The Y key
	 */
	var Y = 'y';

	/**
	 * The Z key
	 */
	var Z = 'z';

	/**
	 * The zero key
	 */
	var Zero = '0';

	/**
	 * The one key
	 */
	var One = '1';

	/**
	 * The two key
	 */
	var Two = '2';

	/**
	 * The three key
	 */
	var Three = '3';

	/**
	 * The four key
	 */
	var Four = '4';

	/**
	 * The five key
	 */
	var Five = '5';

	/**
	 * The six key
	 */
	var Six = '6';

	/**
	 * The seven key
	 */
	var Seven = '7';

	/**
	 * The eight key
	 */
	var Eight = '8';

	/**
	 * The nine key
	 */
	var Nine = '9';

	/**
	 * Space key
	 */
	var Space = 'space';

	/**
	 * Exclamation mark key
	 */
	var ExclamationMark = '!';

	/**
	 * Double quote key
	 */
	var DoubleQuote = '\"';

	/**
	 * Hash key
	 */
	var Hash = '#';

	/**
	 * Dollar key
	 */
	var Dollar = '$';

	/**
	 * Ampersand key
	 */
	var Ampersand = '&';

	/**
	 * Single quote key
	 */
	var SingleQuote = '\'';

	/**
	 * Left parenthesis key
	 */
	var LeftParenthesis = '(';

	/**
	 * Right parenthesis key
	 */
	var RightParenthesis = ')';

	/**
	 * Asterisk key
	 */
	var Asterisk = '*';

	/**
	 * Plus key
	 */
	var Plus = '+';

	/**
	 * Comma key
	 */
	var Comma = ',';

	/**
	 * Hyphen-minus key
	 */
	var Minus = '-';

	/**
	 * Full stop key
	 */
	var Period = '.';

	/**
	 * Slash key
	 */
	var Slash = '/';

	/**
	 * Colon key
	 */
	var Colon = ':';

	/**
	 * Semicolon key
	 */
	var Semicolon = ';';

	/**
	 * Less-than key
	 */
	var LessThan = '<';

	/**
	 * Equal key
	 */
	var Equal = '=';

	/**
	 * Greater-than key
	 */
	var GreaterThan = '>';

	/**
	 * Question mark key
	 */
	var QuestionMark = '?';

	/**
	 * At sign key
	 */
	var At = '@';

	/**
	 * Left square bracket key
	 */
	var LeftBracket = '[';

	/**
	 * Backslash key
	 */
	var Backslash = '\\';

	/**
	 * Right square bracket key
	 */
	var RightBracket = ']';

	/**
	 * Caret key
	 */
	var Caret = '^';

	/**
	 * Underscore key
	 */
	var Underscore = '_';

	/**
	 * Grave accent key
	 */
	var Backtick = '`';

	/**
	 * The numpad zero key
	 */
	var Kp0 = 'kp0';

	/**
	 * The numpad one key
	 */
	var Kp1 = 'kp1';

	/**
	 * The numpad two key
	 */
	var Kp2 = 'kp2';

	/**
	 * The numpad three key
	 */
	var Kp3 = 'kp3';

	/**
	 * The numpad four key
	 */
	var Kp4 = 'kp4';

	/**
	 * The numpad five key
	 */
	var Kp5 = 'kp5';

	/**
	 * The numpad six key
	 */
	var Kp6 = 'kp6';

	/**
	 * The numpad seven key
	 */
	var Kp7 = 'kp7';

	/**
	 * The numpad eight key
	 */
	var Kp8 = 'kp8';

	/**
	 * The numpad nine key
	 */
	var Kp9 = 'kp9';

	/**
	 * The numpad decimal point key
	 */
	var KpPeriod = 'kp.';

	/**
	 * The numpad division key
	 */
	var KpDivision = 'kp/';

	/**
	 * The numpad multiplication key
	 */
	var KpAsterisk = 'kp*';

	/**
	 * The numpad substraction key
	 */
	var KpMinus = 'kp-';

	/**
	 * The numpad addition key
	 */
	var KpPlus = 'kp+';

	/**
	 * The numpad enter key
	 */
	var Kpenter = 'kpenter';

	/**
	 * The numpad equals key
	 */
	var KpEqual = 'kp=';

	/**
	 * Up cursor key
	 */
	var Up = 'up';

	/**
	 * Down cursor key
	 */
	var Down = 'down';

	/**
	 * Right cursor key
	 */
	var Right = 'right';

	/**
	 * Left cursor key
	 */
	var Left = 'left';

	/**
	 * Home key
	 */
	var Home = 'home';

	/**
	 * End key
	 */
	var End = 'end';

	/**
	 * Page up key
	 */
	var Pageup = 'pageup';

	/**
	 * Page down key
	 */
	var Pagedown = 'pagedown';

	/**
	 * Insert key
	 */
	var Insert = 'insert';

	/**
	 * Backspace key
	 */
	var Backspace = 'backspace';

	/**
	 * Tab key
	 */
	var Tab = 'tab';

	/**
	 * Clear key
	 */
	var Clear = 'clear';

	/**
	 * Return key
	 */
	var Return = 'return';

	/**
	 * Delete key
	 */
	var Delete = 'delete';

	/**
	 * The 1st function key
	 */
	var F1 = 'f1';

	/**
	 * The 2nd function key
	 */
	var F2 = 'f2';

	/**
	 * The 3rd function key
	 */
	var F3 = 'f3';

	/**
	 * The 4th function key
	 */
	var F4 = 'f4';

	/**
	 * The 5th function key
	 */
	var F5 = 'f5';

	/**
	 * The 6th function key
	 */
	var F6 = 'f6';

	/**
	 * The 7th function key
	 */
	var F7 = 'f7';

	/**
	 * The 8th function key
	 */
	var F8 = 'f8';

	/**
	 * The 9th function key
	 */
	var F9 = 'f9';

	/**
	 * The 10th function key
	 */
	var F10 = 'f10';

	/**
	 * The 11th function key
	 */
	var F11 = 'f11';

	/**
	 * The 12th function key
	 */
	var F12 = 'f12';

	/**
	 * The 13th function key
	 */
	var F13 = 'f13';

	/**
	 * The 14th function key
	 */
	var F14 = 'f14';

	/**
	 * The 15th function key
	 */
	var F15 = 'f15';

	/**
	 * Num-lock key
	 */
	var Numlock = 'numlock';

	/**
	 * Caps-lock key
	 */
	var Capslock = 'capslock';

	/**
	 * Scroll-lock key
	 */
	var Scrollock = 'scrollock';

	/**
	 * Right shift key
	 */
	var Rshift = 'rshift';

	/**
	 * Left shift key
	 */
	var Lshift = 'lshift';

	/**
	 * Right control key
	 */
	var Rctrl = 'rctrl';

	/**
	 * Left control key
	 */
	var Lctrl = 'lctrl';

	/**
	 * Right alt key
	 */
	var Ralt = 'ralt';

	/**
	 * Left alt key
	 */
	var Lalt = 'lalt';

	/**
	 * Right meta key
	 */
	var Rmeta = 'rmeta';

	/**
	 * Left meta key
	 */
	var Lmeta = 'lmeta';

	/**
	 * Left super key
	 */
	var Lsuper = 'lsuper';

	/**
	 * Right super key
	 */
	var Rsuper = 'rsuper';

	/**
	 * Mode key
	 */
	var Mode = 'mode';

	/**
	 * Compose key
	 */
	var Compose = 'compose';

	/**
	 * Pause key
	 */
	var Pause = 'pause';

	/**
	 * Escape key
	 */
	var Escape = 'escape';

	/**
	 * Help key
	 */
	var Help = 'help';

	/**
	 * Print key
	 */
	var Print = 'print';

	/**
	 * System request key
	 */
	var Sysreq = 'sysreq';

	/**
	 * Break key
	 */
	var Break = 'break';

	/**
	 * Menu key
	 */
	var Menu = 'menu';

	/**
	 * Power key
	 */
	var Power = 'power';

	/**
	 * Euro (&euro;) key
	 */
	var Euro = 'euro';

	/**
	 * Undo key
	 */
	var Undo = 'undo';

	/**
	 * WWW key
	 */
	var Www = 'www';

	/**
	 * Mail key
	 */
	var Mail = 'mail';

	/**
	 * Calculator key
	 */
	var Calculator = 'calculator';

	/**
	 * Application search key
	 */
	var Appsearch = 'appsearch';

	/**
	 * Application home key
	 */
	var Apphome = 'apphome';

	/**
	 * Application back key
	 */
	var Appback = 'appback';

	/**
	 * Application forward key
	 */
	var Appforward = 'appforward';

	/**
	 * Application refresh key
	 */
	var Apprefresh = 'apprefresh';

	/**
	 * Application bookmarks key
	 */
	var Appbookmarks = 'appbookmarks';
}