// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.keyboard;

/**
 * Keyboard scancodes.
 * Scancodes are keyboard layout-independent, so the scancode "w" will be generated if the key in the same place as the "w" key on an American QWERTY keyboard is pressed, no matter what the key is labelled or what the user's operating system settings are.
 * Using scancodes, rather than keycodes, is useful because keyboards with layouts differing from the US/UK layout(s) might have keys that generate 'unknown' keycodes, but the scancodes will still be detected. This however would necessitate having a list for each keyboard layout one would choose to support.
 * One could use textinput or textedited instead, but those only give back the end result of keys used, i.e. you can't get modifiers on their own from it, only the final symbols that were generated.
 */
enum abstract Scancode (String) {

	/**
	 * The 'A' key on an American layout.
	 */
	var A = 'a';

	/**
	 * The 'B' key on an American layout.
	 */
	var B = 'b';

	/**
	 * The 'C' key on an American layout.
	 */
	var C = 'c';

	/**
	 * The 'D' key on an American layout.
	 */
	var D = 'd';

	/**
	 * The 'E' key on an American layout.
	 */
	var E = 'e';

	/**
	 * The 'F' key on an American layout.
	 */
	var F = 'f';

	/**
	 * The 'G' key on an American layout.
	 */
	var G = 'g';

	/**
	 * The 'H' key on an American layout.
	 */
	var H = 'h';

	/**
	 * The 'I' key on an American layout.
	 */
	var I = 'i';

	/**
	 * The 'J' key on an American layout.
	 */
	var J = 'j';

	/**
	 * The 'K' key on an American layout.
	 */
	var K = 'k';

	/**
	 * The 'L' key on an American layout.
	 */
	var L = 'l';

	/**
	 * The 'M' key on an American layout.
	 */
	var M = 'm';

	/**
	 * The 'N' key on an American layout.
	 */
	var N = 'n';

	/**
	 * The 'O' key on an American layout.
	 */
	var O = 'o';

	/**
	 * The 'P' key on an American layout.
	 */
	var P = 'p';

	/**
	 * The 'Q' key on an American layout.
	 */
	var Q = 'q';

	/**
	 * The 'R' key on an American layout.
	 */
	var R = 'r';

	/**
	 * The 'S' key on an American layout.
	 */
	var S = 's';

	/**
	 * The 'T' key on an American layout.
	 */
	var T = 't';

	/**
	 * The 'U' key on an American layout.
	 */
	var U = 'u';

	/**
	 * The 'V' key on an American layout.
	 */
	var V = 'v';

	/**
	 * The 'W' key on an American layout.
	 */
	var W = 'w';

	/**
	 * The 'X' key on an American layout.
	 */
	var X = 'x';

	/**
	 * The 'Y' key on an American layout.
	 */
	var Y = 'y';

	/**
	 * The 'Z' key on an American layout.
	 */
	var Z = 'z';

	/**
	 * The '1' key on an American layout.
	 */
	var One = '1';

	/**
	 * The '2' key on an American layout.
	 */
	var Two = '2';

	/**
	 * The '3' key on an American layout.
	 */
	var Three = '3';

	/**
	 * The '4' key on an American layout.
	 */
	var Four = '4';

	/**
	 * The '5' key on an American layout.
	 */
	var Five = '5';

	/**
	 * The '6' key on an American layout.
	 */
	var Six = '6';

	/**
	 * The '7' key on an American layout.
	 */
	var Seven = '7';

	/**
	 * The '8' key on an American layout.
	 */
	var Eight = '8';

	/**
	 * The '9' key on an American layout.
	 */
	var Nine = '9';

	/**
	 * The '0' key on an American layout.
	 */
	var Zero = '0';

	/**
	 * The 'return' / 'enter' key on an American layout.
	 */
	var Return = 'return';

	/**
	 * The 'escape' key on an American layout.
	 */
	var Escape = 'escape';

	/**
	 * The 'backspace' key on an American layout.
	 */
	var Backspace = 'backspace';

	/**
	 * The 'tab' key on an American layout.
	 */
	var Tab = 'tab';

	/**
	 * The spacebar on an American layout.
	 */
	var Space = 'space';

	/**
	 * The minus key on an American layout.
	 */
	var Minus = '-';

	/**
	 * The equals key on an American layout.
	 */
	var Equal = '=';

	/**
	 * The left-bracket key on an American layout.
	 */
	var LeftBracket = '[';

	/**
	 * The right-bracket key on an American layout.
	 */
	var RightBracket = ']';

	/**
	 * The backslash key on an American layout.
	 */
	var Backslash = '\\';

	/**
	 * The non-U.S. hash scancode.
	 */
	var NonUSHash = 'nonus#';

	/**
	 * The semicolon key on an American layout.
	 */
	var Semicolon = ';';

	/**
	 * The apostrophe key on an American layout.
	 */
	var SingleQuote = '\'';

	/**
	 * The back-tick / grave key on an American layout.
	 */
	var Backtick = '`';

	/**
	 * The comma key on an American layout.
	 */
	var Comma = ',';

	/**
	 * The period key on an American layout.
	 */
	var Period = '.';

	/**
	 * The forward-slash key on an American layout.
	 */
	var Slash = '/';

	/**
	 * The capslock key on an American layout.
	 */
	var Capslock = 'capslock';

	/**
	 * The F1 key on an American layout.
	 */
	var F1 = 'f1';

	/**
	 * The F2 key on an American layout.
	 */
	var F2 = 'f2';

	/**
	 * The F3 key on an American layout.
	 */
	var F3 = 'f3';

	/**
	 * The F4 key on an American layout.
	 */
	var F4 = 'f4';

	/**
	 * The F5 key on an American layout.
	 */
	var F5 = 'f5';

	/**
	 * The F6 key on an American layout.
	 */
	var F6 = 'f6';

	/**
	 * The F7 key on an American layout.
	 */
	var F7 = 'f7';

	/**
	 * The F8 key on an American layout.
	 */
	var F8 = 'f8';

	/**
	 * The F9 key on an American layout.
	 */
	var F9 = 'f9';

	/**
	 * The F10 key on an American layout.
	 */
	var F10 = 'f10';

	/**
	 * The F11 key on an American layout.
	 */
	var F11 = 'f11';

	/**
	 * The F12 key on an American layout.
	 */
	var F12 = 'f12';

	/**
	 * The F13 key on an American layout.
	 */
	var F13 = 'f13';

	/**
	 * The F14 key on an American layout.
	 */
	var F14 = 'f14';

	/**
	 * The F15 key on an American layout.
	 */
	var F15 = 'f15';

	/**
	 * The F16 key on an American layout.
	 */
	var F16 = 'f16';

	/**
	 * The F17 key on an American layout.
	 */
	var F17 = 'f17';

	/**
	 * The F18 key on an American layout.
	 */
	var F18 = 'f18';

	/**
	 * The F19 key on an American layout.
	 */
	var F19 = 'f19';

	/**
	 * The F20 key on an American layout.
	 */
	var F20 = 'f20';

	/**
	 * The F21 key on an American layout.
	 */
	var F21 = 'f21';

	/**
	 * The F22 key on an American layout.
	 */
	var F22 = 'f22';

	/**
	 * The F23 key on an American layout.
	 */
	var F23 = 'f23';

	/**
	 * The F24 key on an American layout.
	 */
	var F24 = 'f24';

	/**
	 * The left control key on an American layout.
	 */
	var Lctrl = 'lctrl';

	/**
	 * The left shift key on an American layout.
	 */
	var Lshift = 'lshift';

	/**
	 * The left alt / option key on an American layout.
	 */
	var Lalt = 'lalt';

	/**
	 * The left GUI (command / windows / super) key on an American layout.
	 */
	var Lgui = 'lgui';

	/**
	 * The right control key on an American layout.
	 */
	var Rctrl = 'rctrl';

	/**
	 * The right shift key on an American layout.
	 */
	var Rshift = 'rshift';

	/**
	 * The right alt / option key on an American layout.
	 */
	var Ralt = 'ralt';

	/**
	 * The right GUI (command / windows / super) key on an American layout.
	 */
	var Rgui = 'rgui';

	/**
	 * The printscreen key on an American layout.
	 */
	var Printscreen = 'printscreen';

	/**
	 * The scroll-lock key on an American layout.
	 */
	var Scrolllock = 'scrolllock';

	/**
	 * The pause key on an American layout.
	 */
	var Pause = 'pause';

	/**
	 * The insert key on an American layout.
	 */
	var Insert = 'insert';

	/**
	 * The home key on an American layout.
	 */
	var Home = 'home';

	/**
	 * The numlock / clear key on an American layout.
	 */
	var Numlock = 'numlock';

	/**
	 * The page-up key on an American layout.
	 */
	var Pageup = 'pageup';

	/**
	 * The forward-delete key on an American layout.
	 */
	var Delete = 'delete';

	/**
	 * The end key on an American layout.
	 */
	var End = 'end';

	/**
	 * The page-down key on an American layout.
	 */
	var Pagedown = 'pagedown';

	/**
	 * The right-arrow key on an American layout.
	 */
	var Right = 'right';

	/**
	 * The left-arrow key on an American layout.
	 */
	var Left = 'left';

	/**
	 * The down-arrow key on an American layout.
	 */
	var Down = 'down';

	/**
	 * The up-arrow key on an American layout.
	 */
	var Up = 'up';

	/**
	 * The non-U.S. backslash scancode.
	 */
	var Nonusbackslash = 'nonusbackslash';

	/**
	 * The application key on an American layout. Windows contextual menu, compose key.
	 */
	var Application = 'application';

	/**
	 * The 'execute' key on an American layout.
	 */
	var Execute = 'execute';

	/**
	 * The 'help' key on an American layout.
	 */
	var Help = 'help';

	/**
	 * The 'menu' key on an American layout.
	 */
	var Menu = 'menu';

	/**
	 * The 'select' key on an American layout.
	 */
	var Select = 'select';

	/**
	 * The 'stop' key on an American layout.
	 */
	var Stop = 'stop';

	/**
	 * The 'again' key on an American layout.
	 */
	var Again = 'again';

	/**
	 * The 'undo' key on an American layout.
	 */
	var Undo = 'undo';

	/**
	 * The 'cut' key on an American layout.
	 */
	var Cut = 'cut';

	/**
	 * The 'copy' key on an American layout.
	 */
	var Copy = 'copy';

	/**
	 * The 'paste' key on an American layout.
	 */
	var Paste = 'paste';

	/**
	 * The 'find' key on an American layout.
	 */
	var Find = 'find';

	/**
	 * The keypad forward-slash key on an American layout.
	 */
	var KpDivision = 'kp/';

	/**
	 * The keypad '*' key on an American layout.
	 */
	var KpAsterisk = 'kp*';

	/**
	 * The keypad minus key on an American layout.
	 */
	var KpMinus = 'kp-';

	/**
	 * The keypad plus key on an American layout.
	 */
	var KpPlus = 'kp+';

	/**
	 * The keypad equals key on an American layout.
	 */
	var KpEqual = 'kp=';

	/**
	 * The keypad enter key on an American layout.
	 */
	var Kpenter = 'kpenter';

	/**
	 * The keypad '1' key on an American layout.
	 */
	var Kp1 = 'kp1';

	/**
	 * The keypad '2' key on an American layout.
	 */
	var Kp2 = 'kp2';

	/**
	 * The keypad '3' key on an American layout.
	 */
	var Kp3 = 'kp3';

	/**
	 * The keypad '4' key on an American layout.
	 */
	var Kp4 = 'kp4';

	/**
	 * The keypad '5' key on an American layout.
	 */
	var Kp5 = 'kp5';

	/**
	 * The keypad '6' key on an American layout.
	 */
	var Kp6 = 'kp6';

	/**
	 * The keypad '7' key on an American layout.
	 */
	var Kp7 = 'kp7';

	/**
	 * The keypad '8' key on an American layout.
	 */
	var Kp8 = 'kp8';

	/**
	 * The keypad '9' key on an American layout.
	 */
	var Kp9 = 'kp9';

	/**
	 * The keypad '0' key on an American layout.
	 */
	var Kp0 = 'kp0';

	/**
	 * The keypad period key on an American layout.
	 */
	var KpPeriod = 'kp.';

	/**
	 * The 1st international key on an American layout. Used on Asian keyboards.
	 */
	var International1 = 'international1';

	/**
	 * The 2nd international key on an American layout.
	 */
	var International2 = 'international2';

	/**
	 * The 3rd international  key on an American layout. Yen.
	 */
	var International3 = 'international3';

	/**
	 * The 4th international key on an American layout.
	 */
	var International4 = 'international4';

	/**
	 * The 5th international key on an American layout.
	 */
	var International5 = 'international5';

	/**
	 * The 6th international key on an American layout.
	 */
	var International6 = 'international6';

	/**
	 * The 7th international key on an American layout.
	 */
	var International7 = 'international7';

	/**
	 * The 8th international key on an American layout.
	 */
	var International8 = 'international8';

	/**
	 * The 9th international key on an American layout.
	 */
	var International9 = 'international9';

	/**
	 * Hangul/English toggle scancode.
	 */
	var Lang1 = 'lang1';

	/**
	 * Hanja conversion scancode.
	 */
	var Lang2 = 'lang2';

	/**
	 * Katakana scancode.
	 */
	var Lang3 = 'lang3';

	/**
	 * Hiragana scancode.
	 */
	var Lang4 = 'lang4';

	/**
	 * Zenkaku/Hankaku scancode.
	 */
	var Lang5 = 'lang5';

	/**
	 * The mute key on an American layout.
	 */
	var Mute = 'mute';

	/**
	 * The volume up key on an American layout.
	 */
	var Volumeup = 'volumeup';

	/**
	 * The volume down key on an American layout.
	 */
	var Volumedown = 'volumedown';

	/**
	 * The audio next track key on an American layout.
	 */
	var Audionext = 'audionext';

	/**
	 * The audio previous track key on an American layout.
	 */
	var Audioprev = 'audioprev';

	/**
	 * The audio stop key on an American layout.
	 */
	var Audiostop = 'audiostop';

	/**
	 * The audio play key on an American layout.
	 */
	var Audioplay = 'audioplay';

	/**
	 * The audio mute key on an American layout.
	 */
	var Audiomute = 'audiomute';

	/**
	 * The media select key on an American layout.
	 */
	var Mediaselect = 'mediaselect';

	/**
	 * The 'WWW' key on an American layout.
	 */
	var Www = 'www';

	/**
	 * The Mail key on an American layout.
	 */
	var Mail = 'mail';

	/**
	 * The calculator key on an American layout.
	 */
	var Calculator = 'calculator';

	/**
	 * The 'computer' key on an American layout.
	 */
	var Computer = 'computer';

	/**
	 * The AC Search key on an American layout.
	 */
	var Acsearch = 'acsearch';

	/**
	 * The AC Home key on an American layout.
	 */
	var Achome = 'achome';

	/**
	 * The AC Back key on an American layout.
	 */
	var Acback = 'acback';

	/**
	 * The AC Forward key on an American layout.
	 */
	var Acforward = 'acforward';

	/**
	 * Th AC Stop key on an American layout.
	 */
	var Acstop = 'acstop';

	/**
	 * The AC Refresh key on an American layout.
	 */
	var Acrefresh = 'acrefresh';

	/**
	 * The AC Bookmarks key on an American layout.
	 */
	var Acbookmarks = 'acbookmarks';

	/**
	 * The system power scancode.
	 */
	var Power = 'power';

	/**
	 * The brightness-down scancode.
	 */
	var Brightnessdown = 'brightnessdown';

	/**
	 * The brightness-up scancode.
	 */
	var Brightnessup = 'brightnessup';

	/**
	 * The display switch scancode.
	 */
	var Displayswitch = 'displayswitch';

	/**
	 * The keyboard illumination toggle scancode.
	 */
	var Kbdillumtoggle = 'kbdillumtoggle';

	/**
	 * The keyboard illumination down scancode.
	 */
	var Kbdillumdown = 'kbdillumdown';

	/**
	 * The keyboard illumination up scancode.
	 */
	var Kbdillumup = 'kbdillumup';

	/**
	 * The eject scancode.
	 */
	var Eject = 'eject';

	/**
	 * The system sleep scancode.
	 */
	var Sleep = 'sleep';

	/**
	 * The alt-erase key on an American layout.
	 */
	var Alterase = 'alterase';

	/**
	 * The sysreq key on an American layout.
	 */
	var Sysreq = 'sysreq';

	/**
	 * The 'cancel' key on an American layout.
	 */
	var Cancel = 'cancel';

	/**
	 * The 'clear' key on an American layout.
	 */
	var Clear = 'clear';

	/**
	 * The 'prior' key on an American layout.
	 */
	var Prior = 'prior';

	/**
	 * The 'return2' key on an American layout.
	 */
	var Return2 = 'return2';

	/**
	 * The 'separator' key on an American layout.
	 */
	var Separator = 'separator';

	/**
	 * The 'out' key on an American layout.
	 */
	var Out = 'out';

	/**
	 * The 'oper' key on an American layout.
	 */
	var Oper = 'oper';

	/**
	 * The 'clearagain' key on an American layout.
	 */
	var Clearagain = 'clearagain';

	/**
	 * The 'crsel' key on an American layout.
	 */
	var Crsel = 'crsel';

	/**
	 * The 'exsel' key on an American layout.
	 */
	var Exsel = 'exsel';

	/**
	 * The keypad 00 key on an American layout.
	 */
	var Kp00 = 'kp00';

	/**
	 * The keypad 000 key on an American layout.
	 */
	var Kp000 = 'kp000';

	/**
	 * The thousands-separator key on an American layout.
	 */
	var Thsousandsseparator = 'thsousandsseparator';

	/**
	 * The decimal separator key on an American layout.
	 */
	var Decimalseparator = 'decimalseparator';

	/**
	 * The currency unit key on an American layout.
	 */
	var Currencyunit = 'currencyunit';

	/**
	 * The currency sub-unit key on an American layout.
	 */
	var Currencysubunit = 'currencysubunit';

	/**
	 * The 'app1' scancode.
	 */
	var App1 = 'app1';

	/**
	 * The 'app2' scancode.
	 */
	var App2 = 'app2';

	/**
	 * An unknown key.
	 */
	var Unknown = 'unknown';
}