// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love;
import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

/**
 * The superclass of all data.
 */
extern class Data extends Object {

	/**
	 * Creates a new copy of the Data object.
	 * @return The new copy.
	 */
	public function clone(): Data;

	/**
	 * Gets an FFI pointer to the Data.
	 * This function should be preferred instead of Data:getPointer because the latter uses light userdata which can't store more all possible memory addresses on some new ARM64 architectures, when LuaJIT is used.
	 * @return A raw void* pointer to the Data, or nil if FFI is unavailable.
	 */
	public function getFFIPointer(): Dynamic;

	/**
	 * Gets a pointer to the Data. Can be used with libraries such as LuaJIT's FFI.
	 * @return A raw pointer to the Data.
	 */
	public function getPointer(): UserData;

	/**
	 * Gets the Data's size in bytes.
	 * @return The size of the Data in bytes.
	 */
	public function getSize(): Float;

	/**
	 * Gets the full Data as a string.
	 * @return The raw data.
	 */
	public function getString(): String;
}