// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love;
import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

/**
 * The superclass of all LÖVE types.
 */
extern class Object extends UserData {

	/**
	 * Destroys the object's Lua reference. The object will be completely deleted if it's not referenced by any other LÖVE object or thread.
	 * This method can be used to immediately clean up resources without waiting for Lua's garbage collector.
	 * @return True if the object was released by this call, false if it had been previously released.
	 */
	public function release(): Bool;

	/**
	 * Gets the type of the object as a string.
	 * @return The type as a string.
	 */
	public function type(): String;

	/**
	 * Checks whether an object is of a certain type. If the object has the type with the specified name in its hierarchy, this function will return true.
	 * @param name The name of the type to check for.
	 * @return True if the object is of the specified type, false otherwise.
	 */
	public function typeOf(name: String): Bool;
}