// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.video;
import haxe.extern.Rest;
import love.filesystem.File;
import lua.Table;
import lua.UserData;

/**
 * This module is responsible for decoding, controlling, and streaming video files.
 * It can't draw the videos, see love.graphics.newVideo and Video objects for that.
 */
@:native('love.video')
extern class Video {

	/**
	 * Creates a new VideoStream. Currently only Ogg Theora video files are supported. VideoStreams can't draw videos, see love.graphics.newVideo for that.
	 * @param filename The file path to the Ogg Theora video file.
	 * @return A new VideoStream.
	 */
	@:overload(function (file: File): VideoStream {})
	public static function newVideoStream(filename: String): VideoStream;
}