// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.video;
import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

/**
 * An object which decodes, streams, and controls Videos.
 */
extern class VideoStream extends Object {

	/**
	 * Gets the filename of the VideoStream.
	 * @return The filename of the VideoStream
	 */
	public function getFilename(): String;

	/**
	 * Gets whether the VideoStream is playing.
	 * @return Whether the VideoStream is playing.
	 */
	public function isPlaying(): Bool;

	/**
	 * Pauses the VideoStream.
	 */
	public function pause(): Void;

	/**
	 * Plays the VideoStream.
	 */
	public function play(): Void;

	/**
	 * Rewinds the VideoStream. Synonym to VideoStream:seek(0).
	 */
	public function rewind(): Void;

	/**
	 * Sets the current playback position of the VideoStream.
	 * @param offset The time in seconds since the beginning of the VideoStream.
	 */
	public function seek(offset: Float): Void;

	/**
	 * Gets the current playback position of the VideoStream.
	 * @return The number of seconds sionce the beginning of the VideoStream.
	 */
	public function tell(): Float;
}