// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.data;
import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

/**
 * Data object containing arbitrary bytes in an contiguous memory.
 * There are currently no LÖVE functions provided for manipulating the contents of a ByteData, but Data:getPointer can be used with LuaJIT's FFI to access and write to the contents directly.
 */
extern class ByteData extends Data {
}