// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.data;

/**
 * Compressed data formats.
 */
enum abstract CompressedDataFormat (String) from String to String {

	/**
	 * The LZ4 compression format. Compresses and decompresses very quickly, but the compression ratio is not the best. LZ4-HC is used when compression level 9 is specified. Some benchmarks are available here.
	 */
	var Lz4 = 'lz4';

	/**
	 * The zlib format is DEFLATE-compressed data with a small bit of header data. Compresses relatively slowly and decompresses moderately quickly, and has a decent compression ratio.
	 */
	var Zlib = 'zlib';

	/**
	 * The gzip format is DEFLATE-compressed data with a slightly larger header than zlib. Since it uses DEFLATE it has the same compression characteristics as the zlib format.
	 */
	var Gzip = 'gzip';

	/**
	 * Raw DEFLATE-compressed data (no header).
	 */
	var Deflate = 'deflate';
}