// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.data;
import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

/**
 * Represents byte data compressed using a specific algorithm.
 * love.data.decompress can be used to de-compress the data (or love.math.decompress in 0.10.2 or earlier).
 */
extern class CompressedData extends Data {

	/**
	 * Gets the compression format of the CompressedData.
	 * @return The format of the CompressedData.
	 */
	public function getFormat(): CompressedDataFormat;
}