// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.data;

/**
 * Return type of various data-returning functions.
 */
enum abstract ContainerType (String) {

	/**
	 * Return type is ByteData.
	 */
	var Data = 'data';

	/**
	 * Return type is string.
	 */
	var String = 'string';
}