// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.data;

/**
 * Encoding format used to encode or decode data.
 */
enum abstract EncodeFormat (String) {

	/**
	 * Encode/decode data as base64 binary-to-text encoding.
	 */
	var Base64 = 'base64';

	/**
	 * Encode/decode data as hexadecimal string.
	 */
	var Hex = 'hex';
}