// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.data;

/**
 * Hash algorithm of love.data.hash.
 */
enum abstract HashFunction (String) {

	/**
	 * MD5 hash algorithm (16 bytes).
	 */
	var Md5 = 'md5';

	/**
	 * SHA1 hash algorithm (20 bytes).
	 */
	var Sha1 = 'sha1';

	/**
	 * SHA2 hash algorithm with message digest size of 224 bits (28 bytes).
	 */
	var Sha224 = 'sha224';

	/**
	 * SHA2 hash algorithm with message digest size of 256 bits (32 bytes).
	 */
	var Sha256 = 'sha256';

	/**
	 * SHA2 hash algorithm with message digest size of 384 bits (48 bytes).
	 */
	var Sha384 = 'sha384';

	/**
	 * SHA2 hash algorithm with message digest size of 512 bits (64 bytes).
	 */
	var Sha512 = 'sha512';
}