// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.sound;
import haxe.extern.Rest;
import love.filesystem.File;
import lua.Table;
import lua.UserData;

/**
 * This module is responsible for decoding sound files. It can't play the sounds, see love.audio for that.
 */
@:native('love.sound')
extern class SoundModule {

	/**
	 * Attempts to find a decoder for the encoded sound data in the specified file.
	 * @param file The file with encoded sound data.
	 * @param buffer The size of each decoded chunk, in bytes.
	 * @return A new Decoder object.
	 */
	@:overload(function (filename: String, ?buffer: Float): Decoder {})
	public static function newDecoder(file: File, ?buffer: Float): Decoder;

	/**
	 * Creates new SoundData from a filepath, File, or Decoder. It's also possible to create SoundData with a custom sample rate, channel and bit depth.
	 * The sound data will be decoded to the memory in a raw format. It is recommended to create only short sounds like effects, as a 3 minute song uses 30 MB of memory this way.
	 * @param filename The file name of the file to load.
	 * @return A new SoundData object.
	 */
	@:overload(function (file: File): SoundData {})
	@:overload(function (decoder: Decoder): SoundData {})
	@:overload(function (samples: Float, ?rate: Float, ?bits: Float, ?channels: Float): SoundData {})
	public static function newSoundData(filename: String): SoundData;
}