// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.image;

/**
 * Encoded image formats.
 */
enum abstract ImageFormat (String) from String to String {

	/**
	 * Targa image format.
	 */
	var Tga = 'tga';

	/**
	 * PNG image format.
	 */
	var Png = 'png';

	/**
	 * JPG image format.
	 */
	var Jpg = 'jpg';

	/**
	 * BMP image format.
	 */
	var Bmp = 'bmp';
}