// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.joystick;

/**
 * Virtual gamepad axes.
 */
enum abstract GamepadAxis (String) from String to String {

	/**
	 * The x-axis of the left thumbstick.
	 */
	var Leftx = 'leftx';

	/**
	 * The y-axis of the left thumbstick.
	 */
	var Lefty = 'lefty';

	/**
	 * The x-axis of the right thumbstick.
	 */
	var Rightx = 'rightx';

	/**
	 * The y-axis of the right thumbstick.
	 */
	var Righty = 'righty';

	/**
	 * Left analog trigger.
	 */
	var Triggerleft = 'triggerleft';

	/**
	 * Right analog trigger.
	 */
	var Triggerright = 'triggerright';
}