// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.joystick;

/**
 * Virtual gamepad buttons.
 */
enum abstract GamepadButton (String) from String to String {

	/**
	 * Bottom face button (A).
	 */
	var A = 'a';

	/**
	 * Right face button (B).
	 */
	var B = 'b';

	/**
	 * Left face button (X).
	 */
	var X = 'x';

	/**
	 * Top face button (Y).
	 */
	var Y = 'y';

	/**
	 * Back button.
	 */
	var Back = 'back';

	/**
	 * Guide button.
	 */
	var Guide = 'guide';

	/**
	 * Start button.
	 */
	var Start = 'start';

	/**
	 * Left stick click button.
	 */
	var Leftstick = 'leftstick';

	/**
	 * Right stick click button.
	 */
	var Rightstick = 'rightstick';

	/**
	 * Left bumper.
	 */
	var Leftshoulder = 'leftshoulder';

	/**
	 * Right bumper.
	 */
	var Rightshoulder = 'rightshoulder';

	/**
	 * D-pad up.
	 */
	var Dpup = 'dpup';

	/**
	 * D-pad down.
	 */
	var Dpdown = 'dpdown';

	/**
	 * D-pad left.
	 */
	var Dpleft = 'dpleft';

	/**
	 * D-pad right.
	 */
	var Dpright = 'dpright';
}