// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.joystick;

/**
 * Types of Joystick inputs.
 */
enum abstract JoystickInputType (String) {

	/**
	 * Analog axis.
	 */
	var Axis = 'axis';

	/**
	 * Button.
	 */
	var Button = 'button';

	/**
	 * 8-direction hat value.
	 */
	var Hat = 'hat';
}