// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.joystick;

/**
 * Joystick hat positions.
 */
enum abstract JoystickHat (String) {

	/**
	 * Centered
	 */
	var C = 'c';

	/**
	 * Down
	 */
	var D = 'd';

	/**
	 * Left
	 */
	var L = 'l';

	/**
	 * Left+Down
	 */
	var Ld = 'ld';

	/**
	 * Left+Up
	 */
	var Lu = 'lu';

	/**
	 * Right
	 */
	var R = 'r';

	/**
	 * Right+Down
	 */
	var Rd = 'rd';

	/**
	 * Right+Up
	 */
	var Ru = 'ru';

	/**
	 * Up
	 */
	var U = 'u';
}