// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.mouse;

/**
 * Types of hardware cursors.
 */
enum abstract CursorType (String) {

	/**
	 * The cursor is using a custom image.
	 */
	var Image = 'image';

	/**
	 * An arrow pointer.
	 */
	var Arrow = 'arrow';

	/**
	 * An I-beam, normally used when mousing over editable or selectable text.
	 */
	var Ibeam = 'ibeam';

	/**
	 * Wait graphic.
	 */
	var Wait = 'wait';

	/**
	 * Small wait cursor with an arrow pointer.
	 */
	var Waitarrow = 'waitarrow';

	/**
	 * Crosshair symbol.
	 */
	var Crosshair = 'crosshair';

	/**
	 * Double arrow pointing to the top-left and bottom-right.
	 */
	var Sizenwse = 'sizenwse';

	/**
	 * Double arrow pointing to the top-right and bottom-left.
	 */
	var Sizenesw = 'sizenesw';

	/**
	 * Double arrow pointing left and right.
	 */
	var Sizewe = 'sizewe';

	/**
	 * Double arrow pointing up and down.
	 */
	var Sizens = 'sizens';

	/**
	 * Four-pointed arrow pointing up, down, left, and right.
	 */
	var Sizeall = 'sizeall';

	/**
	 * Slashed circle or crossbones.
	 */
	var No = 'no';

	/**
	 * Hand symbol.
	 */
	var Hand = 'hand';
}