// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.mouse;
import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

/**
 * Represents a hardware cursor.
 */
extern class Cursor extends Object {

	/**
	 * Gets the type of the Cursor.
	 * @return The type of the Cursor.
	 */
	public function getType(): CursorType;
}