// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.touch;
import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

/**
 * Provides an interface to touch-screen presses.
 */
@:native('love.touch')
extern class Touch {

	/**
	 * Gets the current position of the specified touch-press, in pixels.
	 * @param id The identifier of the touch-press. Use love.touch.getTouches, love.touchpressed, or love.touchmoved to obtain touch id values.
	 */
	public static function getPosition(id: UserData): TouchGetPositionResult;

	/**
	 * Gets the current pressure of the specified touch-press.
	 * @param id The identifier of the touch-press. Use love.touch.getTouches, love.touchpressed, or love.touchmoved to obtain touch id values.
	 * @return The pressure of the touch-press. Most touch screens aren't pressure sensitive, in which case the pressure will be 1.
	 */
	public static function getPressure(id: UserData): Float;

	/**
	 * Gets a list of all active touch-presses.
	 * @return A list of active touch-press id values, which can be used with love.touch.getPosition.
	 */
	public static function getTouches(): Table<Dynamic, Dynamic>;
}

@:multiReturn
extern class TouchGetPositionResult {
	var x: Float;
	var y: Float;
}