// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.event;

/**
 * Arguments to love.event.push() and the like.
 * Since 0.8.0, event names are no longer abbreviated.
 */
enum abstract Event (String) {

	/**
	 * Window focus gained or lost
	 */
	var Focus = 'focus';

	/**
	 * Joystick pressed
	 */
	var Joystickpressed = 'joystickpressed';

	/**
	 * Joystick released
	 */
	var Joystickreleased = 'joystickreleased';

	/**
	 * Key pressed
	 */
	var Keypressed = 'keypressed';

	/**
	 * Key released
	 */
	var Keyreleased = 'keyreleased';

	/**
	 * Mouse pressed
	 */
	var Mousepressed = 'mousepressed';

	/**
	 * Mouse released
	 */
	var Mousereleased = 'mousereleased';

	/**
	 * Quit
	 */
	var Quit = 'quit';

	/**
	 * Window size changed by the user
	 */
	var Resize = 'resize';

	/**
	 * Window is minimized or un-minimized by the user
	 */
	var Visible = 'visible';

	/**
	 * Window mouse focus gained or lost
	 */
	var Mousefocus = 'mousefocus';

	/**
	 * A Lua error has occurred in a thread
	 */
	var Threaderror = 'threaderror';

	/**
	 * Joystick connected
	 */
	var Joystickadded = 'joystickadded';

	/**
	 * Joystick disconnected
	 */
	var Joystickremoved = 'joystickremoved';

	/**
	 * Joystick axis motion
	 */
	var Joystickaxis = 'joystickaxis';

	/**
	 * Joystick hat pressed
	 */
	var Joystickhat = 'joystickhat';

	/**
	 * Joystick's virtual gamepad button pressed
	 */
	var Gamepadpressed = 'gamepadpressed';

	/**
	 * Joystick's virtual gamepad button released
	 */
	var Gamepadreleased = 'gamepadreleased';

	/**
	 * Joystick's virtual gamepad axis moved
	 */
	var Gamepadaxis = 'gamepadaxis';

	/**
	 * User entered text
	 */
	var Textinput = 'textinput';

	/**
	 * Mouse position changed
	 */
	var Mousemoved = 'mousemoved';

	/**
	 * Running out of memory on mobile devices system
	 */
	var Lowmemory = 'lowmemory';

	/**
	 * Candidate text for an IME changed
	 */
	var Textedited = 'textedited';

	/**
	 * Mouse wheel moved
	 */
	var Wheelmoved = 'wheelmoved';

	/**
	 * Touch screen touched
	 */
	var Touchpressed = 'touchpressed';

	/**
	 * Touch screen stop touching
	 */
	var Touchreleased = 'touchreleased';

	/**
	 * Touch press moved inside touch screen
	 */
	var Touchmoved = 'touchmoved';

	/**
	 * Directory is dragged and dropped onto the window
	 */
	var Directorydropped = 'directorydropped';

	/**
	 * File is dragged and dropped onto the window.
	 */
	var Filedropped = 'filedropped';

	/**
	 * Joystick pressed
	 */
	var Jp = 'jp';

	/**
	 * Joystick released
	 */
	var Jr = 'jr';

	/**
	 * Key pressed
	 */
	var Kp = 'kp';

	/**
	 * Key released
	 */
	var Kr = 'kr';

	/**
	 * Mouse pressed
	 */
	var Mp = 'mp';

	/**
	 * Mouse released
	 */
	var Mr = 'mr';

	/**
	 * Quit
	 */
	var Q = 'q';

	/**
	 * Window focus gained or lost
	 */
	var F = 'f';
}