// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.math;

/**
 * The layout of matrix elements (row-major or column-major).
 */
enum abstract MatrixLayout (String) {

	/**
	 * The matrix is row-major:
	 */
	var Row = 'row';

	/**
	 * The matrix is column-major:
	 */
	var Column = 'column';
}