// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.physics;

/**
 * The types of a Body. 
 */
enum abstract BodyType (String) {

	/**
	 * Static bodies do not move.
	 */
	var Static = 'static';

	/**
	 * Dynamic bodies collide with all bodies.
	 */
	var Dynamic = 'dynamic';

	/**
	 * Kinematic bodies only collide with dynamic bodies.
	 */
	var Kinematic = 'kinematic';
}