// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.physics;
import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

/**
 * Circle extends Shape and adds a radius and a local position.
 */
extern class CircleShape extends Shape {

	/**
	 * Gets the center point of the circle shape.
	 */
	public function getPoint(): CircleShapeGetPointResult;

	/**
	 * Gets the radius of the circle shape.
	 * @return The radius of the circle
	 */
	public function getRadius(): Float;

	/**
	 * Sets the location of the center of the circle shape.
	 * @param x The x-component of the new center point of the circle.
	 * @param y The y-component of the new center point of the circle.
	 */
	public function setPoint(x: Float, y: Float): Void;

	/**
	 * Sets the radius of the circle.
	 * @param radius The radius of the circle
	 */
	public function setRadius(radius: Float): Void;
}