// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.physics;
import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

/**
 * Keeps two bodies at the same distance.
 */
extern class DistanceJoint extends Joint {

	/**
	 * Gets the damping ratio.
	 * @return The damping ratio.
	 */
	public function getDampingRatio(): Float;

	/**
	 * Gets the response speed.
	 * @return The response speed.
	 */
	public function getFrequency(): Float;

	/**
	 * Gets the equilibrium distance between the two Bodies.
	 * @return The length between the two Bodies.
	 */
	public function getLength(): Float;

	/**
	 * Sets the damping ratio.
	 * @param ratio The damping ratio.
	 */
	public function setDampingRatio(ratio: Float): Void;

	/**
	 * Sets the response speed.
	 * @param Hz The response speed.
	 */
	public function setFrequency(Hz: Float): Void;

	/**
	 * Sets the equilibrium distance between the two Bodies.
	 * @param l The length between the two Bodies.
	 */
	public function setLength(l: Float): Void;
}