// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.physics;
import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

/**
 * A EdgeShape is a line segment. They can be used to create the boundaries of your terrain. The shape does not have volume and can only collide with PolygonShape and CircleShape.
 */
extern class EdgeShape extends Shape {

	/**
	 * Gets the vertex that establishes a connection to the next shape.
	 * Setting next and previous EdgeShape vertices can help prevent unwanted collisions when a flat shape slides along the edge and moves over to the new shape.
	 */
	public function getNextVertex(): EdgeShapeGetNextVertexResult;

	/**
	 * Returns the local coordinates of the edge points.
	 */
	public function getPoints(): EdgeShapeGetPointsResult;

	/**
	 * Gets the vertex that establishes a connection to the previous shape.
	 * Setting next and previous EdgeShape vertices can help prevent unwanted collisions when a flat shape slides along the edge and moves over to the new shape.
	 */
	public function getPreviousVertex(): EdgeShapeGetPreviousVertexResult;

	/**
	 * Sets a vertex that establishes a connection to the next shape.
	 * This can help prevent unwanted collisions when a flat shape slides along the edge and moves over to the new shape.
	 * @param x The x-component of the vertex.
	 * @param y The y-component of the vertex.
	 */
	public function setNextVertex(x: Float, y: Float): Void;

	/**
	 * Sets a vertex that establishes a connection to the previous shape.
	 * This can help prevent unwanted collisions when a flat shape slides along the edge and moves over to the new shape.
	 * @param x The x-component of the vertex.
	 * @param y The y-component of the vertex.
	 */
	public function setPreviousVertex(x: Float, y: Float): Void;
}

@:multiReturn
extern class EdgeShapeGetPreviousVertexResult {
	var x: Float;
	var y: Float;
}

@:multiReturn
extern class EdgeShapeGetPointsResult {
	var x1: Float;
	var y1: Float;
	var x2: Float;
	var y2: Float;
}

@:multiReturn
extern class EdgeShapeGetNextVertexResult {
	var x: Float;
	var y: Float;
}