// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.physics;
import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

/**
 * A FrictionJoint applies friction to a body.
 */
extern class FrictionJoint extends Joint {

	/**
	 * Gets the maximum friction force in Newtons.
	 * @return Maximum force in Newtons.
	 */
	public function getMaxForce(): Float;

	/**
	 * Gets the maximum friction torque in Newton-meters.
	 * @return Maximum torque in Newton-meters.
	 */
	public function getMaxTorque(): Float;

	/**
	 * Sets the maximum friction force in Newtons.
	 * @param maxForce Max force in Newtons.
	 */
	public function setMaxForce(maxForce: Float): Void;

	/**
	 * Sets the maximum friction torque in Newton-meters.
	 * @param torque Maximum torque in Newton-meters.
	 */
	public function setMaxTorque(torque: Float): Void;
}