// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.physics;
import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

/**
 * Keeps bodies together in such a way that they act like gears.
 */
extern class GearJoint extends Joint {

	/**
	 * Get the Joints connected by this GearJoint.
	 */
	public function getJoints(): GearJointGetJointsResult;

	/**
	 * Get the ratio of a gear joint.
	 * @return The ratio of the joint.
	 */
	public function getRatio(): Float;

	/**
	 * Set the ratio of a gear joint.
	 * @param ratio The new ratio of the joint.
	 */
	public function setRatio(ratio: Float): Void;
}

@:multiReturn
extern class GearJointGetJointsResult {
	var joint1: Joint;
	var joint2: Joint;
}