// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.physics;

/**
 * Different types of joints.
 */
enum abstract JointType (String) from String to String {

	/**
	 * A DistanceJoint.
	 */
	var Distance = 'distance';

	/**
	 * A FrictionJoint.
	 */
	var Friction = 'friction';

	/**
	 * A GearJoint.
	 */
	var Gear = 'gear';

	/**
	 * A MouseJoint.
	 */
	var Mouse = 'mouse';

	/**
	 * A PrismaticJoint.
	 */
	var Prismatic = 'prismatic';

	/**
	 * A PulleyJoint.
	 */
	var Pulley = 'pulley';

	/**
	 * A RevoluteJoint.
	 */
	var Revolute = 'revolute';

	/**
	 * A RopeJoint.
	 */
	var Rope = 'rope';

	/**
	 * A WeldJoint.
	 */
	var Weld = 'weld';
}