// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.physics;
import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

/**
 * For controlling objects with the mouse.
 */
extern class MouseJoint extends Joint {

	/**
	 * Returns the damping ratio.
	 * @return The new damping ratio.
	 */
	public function getDampingRatio(): Float;

	/**
	 * Returns the frequency.
	 * @return The frequency in hertz.
	 */
	public function getFrequency(): Float;

	/**
	 * Gets the highest allowed force.
	 * @return The max allowed force.
	 */
	public function getMaxForce(): Float;

	/**
	 * Gets the target point.
	 */
	public function getTarget(): MouseJointGetTargetResult;

	/**
	 * Sets a new damping ratio.
	 * @param ratio The new damping ratio.
	 */
	public function setDampingRatio(ratio: Float): Void;

	/**
	 * Sets a new frequency.
	 * @param freq The new frequency in hertz.
	 */
	public function setFrequency(freq: Float): Void;

	/**
	 * Sets the highest allowed force.
	 * @param f The max allowed force.
	 */
	public function setMaxForce(f: Float): Void;

	/**
	 * Sets the target point.
	 * @param x The x-component of the target.
	 * @param y The y-component of the target.
	 */
	public function setTarget(x: Float, y: Float): Void;
}

@:multiReturn
extern class MouseJointGetTargetResult {
	var x: Float;
	var y: Float;
}