// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.physics;
import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

/**
 * A PolygonShape is a convex polygon with up to 8 vertices.
 */
extern class PolygonShape extends Shape {

	/**
	 * Get the local coordinates of the polygon's vertices.
	 * This function has a variable number of return values. It can be used in a nested fashion with love.graphics.polygon.
	 */
	public function getPoints(): PolygonShapeGetPointsResult;
}