// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.physics;
import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

/**
 * Allows you to simulate bodies connected through pulleys.
 */
extern class PulleyJoint extends Joint {

	/**
	 * Get the total length of the rope.
	 * @return The length of the rope in the joint.
	 */
	public function getConstant(): Float;

	/**
	 * Get the ground anchor positions in world coordinates.
	 */
	public function getGroundAnchors(): PulleyJointGetGroundAnchorsResult;

	/**
	 * Get the current length of the rope segment attached to the first body.
	 * @return The length of the rope segment.
	 */
	public function getLengthA(): Float;

	/**
	 * Get the current length of the rope segment attached to the second body.
	 * @return The length of the rope segment.
	 */
	public function getLengthB(): Float;

	/**
	 * Get the maximum lengths of the rope segments.
	 */
	public function getMaxLengths(): PulleyJointGetMaxLengthsResult;

	/**
	 * Get the pulley ratio.
	 * @return The pulley ratio of the joint.
	 */
	public function getRatio(): Float;

	/**
	 * Set the total length of the rope.
	 * Setting a new length for the rope updates the maximum length values of the joint.
	 * @param length The new length of the rope in the joint.
	 */
	public function setConstant(length: Float): Void;

	/**
	 * Set the maximum lengths of the rope segments.
	 * The physics module also imposes maximum values for the rope segments. If the parameters exceed these values, the maximum values are set instead of the requested values.
	 * @param max1 The new maximum length of the first segment.
	 * @param max2 The new maximum length of the second segment.
	 */
	public function setMaxLengths(max1: Float, max2: Float): Void;

	/**
	 * Set the pulley ratio.
	 * @param ratio The new pulley ratio of the joint.
	 */
	public function setRatio(ratio: Float): Void;
}

@:multiReturn
extern class PulleyJointGetMaxLengthsResult {
	var len1: Float;
	var len2: Float;
}

@:multiReturn
extern class PulleyJointGetGroundAnchorsResult {
	var a1x: Float;
	var a1y: Float;
	var a2x: Float;
	var a2y: Float;
}