// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.physics;
import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

/**
 * Allow two Bodies to revolve around a shared point.
 */
extern class RevoluteJoint extends Joint {

	/**
	 * Checks whether limits are enabled.
	 * @return True if enabled, false otherwise.
	 */
	public function areLimitsEnabled(): Bool;

	/**
	 * Get the current joint angle.
	 * @return The joint angle in radians.
	 */
	public function getJointAngle(): Float;

	/**
	 * Get the current joint angle speed.
	 * @return Joint angle speed in radians/second.
	 */
	public function getJointSpeed(): Float;

	/**
	 * Gets the joint limits.
	 */
	public function getLimits(): RevoluteJointGetLimitsResult;

	/**
	 * Gets the lower limit.
	 * @return The lower limit, in radians.
	 */
	public function getLowerLimit(): Float;

	/**
	 * Gets the maximum motor force.
	 * @return The maximum motor force, in Nm.
	 */
	public function getMaxMotorTorque(): Float;

	/**
	 * Gets the motor speed.
	 * @return The motor speed, radians per second.
	 */
	public function getMotorSpeed(): Float;

	/**
	 * Get the current motor force.
	 * @return The current motor force, in Nm.
	 */
	public function getMotorTorque(): Float;

	/**
	 * Gets the reference angle.
	 * @return The reference angle in radians.
	 */
	public function getReferenceAngle(): Float;

	/**
	 * Gets the upper limit.
	 * @return The upper limit, in radians.
	 */
	public function getUpperLimit(): Float;

	/**
	 * Checks whether limits are enabled.
	 * @return True if enabled, false otherwise.
	 */
	public function hasLimitsEnabled(): Bool;

	/**
	 * Checks whether the motor is enabled.
	 * @return True if enabled, false if disabled.
	 */
	public function isMotorEnabled(): Bool;

	/**
	 * Sets the limits.
	 * @param lower The lower limit, in radians.
	 * @param upper The upper limit, in radians.
	 */
	public function setLimits(lower: Float, upper: Float): Void;

	/**
	 * Enables/disables the joint limit.
	 * @param enable True to enable, false to disable.
	 */
	public function setLimitsEnabled(enable: Bool): Void;

	/**
	 * Sets the lower limit.
	 * @param lower The lower limit, in radians.
	 */
	public function setLowerLimit(lower: Float): Void;

	/**
	 * Set the maximum motor force.
	 * @param f The maximum motor force, in Nm.
	 */
	public function setMaxMotorTorque(f: Float): Void;

	/**
	 * Enables/disables the joint motor.
	 * @param enable True to enable, false to disable.
	 */
	public function setMotorEnabled(enable: Bool): Void;

	/**
	 * Sets the motor speed.
	 * @param s The motor speed, radians per second.
	 */
	public function setMotorSpeed(s: Float): Void;

	/**
	 * Sets the upper limit.
	 * @param upper The upper limit, in radians.
	 */
	public function setUpperLimit(upper: Float): Void;
}

@:multiReturn
extern class RevoluteJointGetLimitsResult {
	var lower: Float;
	var upper: Float;
}