// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.physics;
import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

/**
 * The RopeJoint enforces a maximum distance between two points on two bodies. It has no other effect.
 */
extern class RopeJoint extends Joint {

	/**
	 * Gets the maximum length of a RopeJoint.
	 * @return The maximum length of the RopeJoint.
	 */
	public function getMaxLength(): Float;

	/**
	 * Sets the maximum length of a RopeJoint.
	 * @param maxLength The new maximum length of the RopeJoint.
	 */
	public function setMaxLength(maxLength: Float): Void;
}