// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.physics;

/**
 * The different types of Shapes, as returned by Shape:getType.
 */
enum abstract ShapeType (String) {

	/**
	 * The Shape is a CircleShape.
	 */
	var Circle = 'circle';

	/**
	 * The Shape is a PolygonShape.
	 */
	var Polygon = 'polygon';

	/**
	 * The Shape is a EdgeShape.
	 */
	var Edge = 'edge';

	/**
	 * The Shape is a ChainShape.
	 */
	var Chain = 'chain';
}