// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.physics;
import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

/**
 * A WeldJoint essentially glues two bodies together.
 */
extern class WeldJoint extends Joint {

	/**
	 * Returns the damping ratio of the joint.
	 * @return The damping ratio.
	 */
	public function getDampingRatio(): Float;

	/**
	 * Returns the frequency.
	 * @return The frequency in hertz.
	 */
	public function getFrequency(): Float;

	/**
	 * Gets the reference angle.
	 * @return The reference angle in radians.
	 */
	public function getReferenceAngle(): Float;

	/**
	 * Sets a new damping ratio.
	 * @param ratio The new damping ratio.
	 */
	public function setDampingRatio(ratio: Float): Void;

	/**
	 * Sets a new frequency.
	 * @param freq The new frequency in hertz.
	 */
	public function setFrequency(freq: Float): Void;
}