// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.system;

/**
 * The basic state of the system's power supply.
 */
enum abstract PowerState (String) {

	/**
	 * Cannot determine power status.
	 */
	var Unknown = 'unknown';

	/**
	 * Not plugged in, running on a battery.
	 */
	var Battery = 'battery';

	/**
	 * Plugged in, no battery available.
	 */
	var Nobattery = 'nobattery';

	/**
	 * Plugged in, charging battery.
	 */
	var Charging = 'charging';

	/**
	 * Plugged in, battery is fully charged.
	 */
	var Charged = 'charged';
}