// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.timer;
import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

/**
 * Provides an interface to the user's clock.
 */
@:native('love.timer')
extern class Timer {

	/**
	 * Returns the average delta time (seconds per frame) over the last second.
	 * @return The average delta time over the last second.
	 */
	public static function getAverageDelta(): Float;

	/**
	 * Returns the time between the last two frames.
	 * @return The time passed (in seconds).
	 */
	public static function getDelta(): Float;

	/**
	 * Returns the current frames per second.
	 * @return The current FPS.
	 */
	public static function getFPS(): Float;

	/**
	 * Returns the value of a timer with an unspecified starting time.
	 * This function should only be used to calculate differences between points in time, as the starting time of the timer is unknown.
	 * @return The time in seconds. Given as a decimal, accurate to the microsecond.
	 */
	public static function getTime(): Float;

	/**
	 * Pauses the current thread for the specified amount of time.
	 * @param s Seconds to sleep for.
	 */
	public static function sleep(s: Float): Void;

	/**
	 * Measures the time between two frames.
	 * Calling this changes the return value of love.timer.getDelta.
	 * @return The time passed (in seconds).
	 */
	public static function step(): Float;
}