// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.graphics;

/**
 * Text alignment.
 */
enum abstract AlignMode (String) {

	/**
	 * Align text center.
	 */
	var Center = 'center';

	/**
	 * Align text left.
	 */
	var Left = 'left';

	/**
	 * Align text right.
	 */
	var Right = 'right';

	/**
	 * Align text both left and right.
	 */
	var Justify = 'justify';
}