// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.graphics;

/**
 * Different types of arcs that can be drawn.
 */
enum abstract ArcType (String) {

	/**
	 * The arc is drawn like a slice of pie, with the arc circle connected to the center at its end-points.
	 */
	var Pie = 'pie';

	/**
	 * The arc circle's two end-points are unconnected when the arc is drawn as a line. Behaves like the "closed" arc type when the arc is drawn in filled mode.
	 */
	var Open = 'open';

	/**
	 * The arc circle's two end-points are connected to each other.
	 */
	var Closed = 'closed';
}