// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.graphics;

/**
 * Types of particle area spread distribution.
 */
enum abstract AreaSpreadDistribution (String) {

	/**
	 * Uniform distribution.
	 */
	var Uniform = 'uniform';

	/**
	 * Normal (gaussian) distribution.
	 */
	var Normal = 'normal';

	/**
	 * Uniform distribution in an ellipse.
	 */
	var Ellipse = 'ellipse';

	/**
	 * Distribution in an ellipse with particles spawning at the edges of the ellipse.
	 */
	var Borderellipse = 'borderellipse';

	/**
	 * Distribution in a rectangle with particles spawning at the edges of the rectangle.
	 */
	var Borderrectangle = 'borderrectangle';

	/**
	 * No distribution - area spread is disabled.
	 */
	var None = 'none';
}