// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.graphics;

/**
 * Different ways to do color blending. See BlendAlphaMode and the BlendMode Formulas for additional notes.
 */
enum abstract BlendMode (String) from String to String {

	/**
	 * Alpha blending (normal). The alpha of what's drawn determines its opacity.
	 */
	var Alpha = 'alpha';

	/**
	 * The colors of what's drawn completely replace what was on the screen, with no additional blending. The BlendAlphaMode specified in love.graphics.setBlendMode still affects what happens.
	 */
	var Replace = 'replace';

	/**
	 * 'Screen' blending.
	 */
	var Screen = 'screen';

	/**
	 * The pixel colors of what's drawn are added to the pixel colors already on the screen. The alpha of the screen is not modified.
	 */
	var Add = 'add';

	/**
	 * The pixel colors of what's drawn are subtracted from the pixel colors already on the screen. The alpha of the screen is not modified.
	 */
	var Subtract = 'subtract';

	/**
	 * The pixel colors of what's drawn are multiplied with the pixel colors already on the screen (darkening them). The alpha of drawn objects is multiplied with the alpha of the screen rather than determining how much the colors on the screen are affected, even when the "alphamultiply" BlendAlphaMode is used.
	 */
	var Multiply = 'multiply';

	/**
	 * The pixel colors of what's drawn are compared to the existing pixel colors, and the larger of the two values for each color component is used. Only works when the "premultiplied" BlendAlphaMode is used in love.graphics.setBlendMode.
	 */
	var Lighten = 'lighten';

	/**
	 * The pixel colors of what's drawn are compared to the existing pixel colors, and the smaller of the two values for each color component is used. Only works when the "premultiplied" BlendAlphaMode is used in love.graphics.setBlendMode.
	 */
	var Darken = 'darken';

	/**
	 * Additive blend mode.
	 */
	var Additive = 'additive';

	/**
	 * Subtractive blend mode.
	 */
	var Subtractive = 'subtractive';

	/**
	 * Multiply blend mode.
	 */
	var Multiplicative = 'multiplicative';

	/**
	 * Premultiplied alpha blend mode.
	 */
	var Premultiplied = 'premultiplied';
}