// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.graphics;

/**
 * Different types of per-pixel stencil test and depth test comparisons. The pixels of an object will be drawn if the comparison succeeds, for each pixel that the object touches.
 */
enum abstract CompareMode (String) from String to String {

	/**
	 * * stencil tests: the stencil value of the pixel must be equal to the supplied value.
	 * * depth tests: the depth value of the drawn object at that pixel must be equal to the existing depth value of that pixel.
	 */
	var Equal = 'equal';

	/**
	 * * stencil tests: the stencil value of the pixel must not be equal to the supplied value.
	 * * depth tests: the depth value of the drawn object at that pixel must not be equal to the existing depth value of that pixel.
	 */
	var Notequal = 'notequal';

	/**
	 * * stencil tests: the stencil value of the pixel must be less than the supplied value.
	 * * depth tests: the depth value of the drawn object at that pixel must be less than the existing depth value of that pixel.
	 */
	var Less = 'less';

	/**
	 * * stencil tests: the stencil value of the pixel must be less than or equal to the supplied value.
	 * * depth tests: the depth value of the drawn object at that pixel must be less than or equal to the existing depth value of that pixel.
	 */
	var Lequal = 'lequal';

	/**
	 * * stencil tests: the stencil value of the pixel must be greater than or equal to the supplied value.
	 * * depth tests: the depth value of the drawn object at that pixel must be greater than or equal to the existing depth value of that pixel.
	 */
	var Gequal = 'gequal';

	/**
	 * * stencil tests: the stencil value of the pixel must be greater than the supplied value.
	 * * depth tests: the depth value of the drawn object at that pixel must be greater than the existing depth value of that pixel.
	 */
	var Greater = 'greater';

	/**
	 * Objects will never be drawn.
	 */
	var Never = 'never';

	/**
	 * Objects will always be drawn. Effectively disables the depth or stencil test.
	 */
	var Always = 'always';
}