// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.graphics;

/**
 * How Mesh geometry is culled when rendering.
 */
enum abstract CullMode (String) from String to String {

	/**
	 * Back-facing triangles in Meshes are culled (not rendered). The vertex order of a triangle determines whether it is back- or front-facing.
	 */
	var Back = 'back';

	/**
	 * Front-facing triangles in Meshes are culled.
	 */
	var Front = 'front';

	/**
	 * Both back- and front-facing triangles in Meshes are rendered.
	 */
	var None = 'none';
}