// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.graphics;

/**
 * Controls whether shapes are drawn as an outline, or filled.
 */
enum abstract DrawMode (String) {

	/**
	 * Draw filled shape.
	 */
	var Fill = 'fill';

	/**
	 * Draw outlined shape.
	 */
	var Line = 'line';
}