// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.graphics;
import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

/**
 * Superclass for all things that can be drawn on screen. This is an abstract type that can't be created directly.
 */
extern class Drawable extends Object {
}