// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.graphics;

/**
 * How the image is filtered when scaling.
 */
enum abstract FilterMode (String) {

	/**
	 * Scale image with linear interpolation.
	 */
	var Linear = 'linear';

	/**
	 * Scale image with nearest neighbor interpolation.
	 */
	var Nearest = 'nearest';
}