// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.graphics;
import haxe.extern.Rest;
import love.Data;
import love.filesystem.File;
import love.filesystem.FileData;
import love.font.HintingMode;
import love.font.Rasterizer;
import love.image.CompressedImageData;
import love.image.ImageData;
import love.math.Transform;
import love.thread.Channel;
import love.video.VideoStream;
import lua.Table;
import lua.UserData;

/**
 * The primary responsibility for the love.graphics module is the drawing of lines, shapes, text, Images and other Drawable objects onto the screen. Its secondary responsibilities include loading external files (including Images and Fonts) into memory, creating specialized objects (such as ParticleSystems or Canvases) and managing screen geometry.
 * LÖVE's coordinate system is rooted in the upper-left corner of the screen, which is at location (0, 0). The x axis is horizontal: larger values are further to the right. The y axis is vertical: larger values are further towards the bottom.
 * In many cases, you draw images or shapes in terms of their upper-left corner.
 * Many of the functions are used to manipulate the graphics coordinate system, which is essentially the way coordinates are mapped to the display. You can change the position, scale, and even rotation in this way.
 */
@:native('love.graphics')
extern class GraphicsModule {

	/**
	 * Applies the given Transform object to the current coordinate transformation.
	 * This effectively multiplies the existing coordinate transformation's matrix with the Transform object's internal matrix to produce the new coordinate transformation.
	 * @param transform The Transform object to apply to the current graphics coordinate transform.
	 */
	public static function applyTransform(transform: Transform): Void;

	/**
	 * Draws a filled or unfilled arc at position (x, y). The arc is drawn from angle1 to angle2 in radians. The segments parameter determines how many segments are used to draw the arc. The more segments, the smoother the edge.
	 * @param drawmode How to draw the arc.
	 * @param x The position of the center along x-axis.
	 * @param y The position of the center along y-axis.
	 * @param radius Radius of the arc.
	 * @param angle1 The angle at which the arc begins.
	 * @param angle2 The angle at which the arc terminates.
	 * @param segments The number of segments used for drawing the arc.
	 */
	@:overload(function (drawmode: DrawMode, arctype: ArcType, x: Float, y: Float, radius: Float, angle1: Float, angle2: Float, ?segments: Float): Void {})
	public static function arc(drawmode: DrawMode, x: Float, y: Float, radius: Float, angle1: Float, angle2: Float, ?segments: Float): Void;

	/**
	 * Creates a screenshot once the current frame is done (after love.draw has finished).
	 * Since this function enqueues a screenshot capture rather than executing it immediately, it can be called from an input callback or love.update and it will still capture all of what's drawn to the screen in that frame.
	 * @param filename The filename to save the screenshot to. The encoded image type is determined based on the extension of the filename, and must be one of the ImageFormats.
	 */
	@:overload(function (callback: (imageData: ImageData) -> Void): Void {})
	@:overload(function (channel: Channel): Void {})
	public static function captureScreenshot(filename: String): Void;

	/**
	 * Draws a circle.
	 * @param mode How to draw the circle.
	 * @param x The position of the center along x-axis.
	 * @param y The position of the center along y-axis.
	 * @param radius The radius of the circle.
	 */
	@:overload(function (mode: DrawMode, x: Float, y: Float, radius: Float, segments: Float): Void {})
	public static function circle(mode: DrawMode, x: Float, y: Float, radius: Float): Void;

	/**
	 * Clears the screen or active Canvas to the specified color.
	 * This function is called automatically before love.draw in the default love.run function. See the example in love.run for a typical use of this function.
	 * Note that the scissor area bounds the cleared region.
	 * In versions prior to 11.0, color component values were within the range of 0 to 255 instead of 0 to 1.
	 * In versions prior to background color instead.
	 */
	@:overload(function (r: Float, g: Float, b: Float, ?a: Float, ?clearstencil: Bool, ?cleardepth: Bool): Void {})
	@:overload(function (color: Table<Dynamic, Dynamic>, args: Rest<Table<Dynamic, Dynamic>>, ?clearstencil: Bool, ?cleardepth: Bool): Void {})
	@:overload(function (clearcolor: Bool, clearstencil: Bool, cleardepth: Bool): Void {})
	public static function clear(): Void;

	/**
	 * Discards (trashes) the contents of the screen or active Canvas. This is a performance optimization function with niche use cases.
	 * If the active Canvas has just been changed and the 'replace' BlendMode is about to be used to draw something which covers the entire screen, calling love.graphics.discard rather than calling love.graphics.clear or doing nothing may improve performance on mobile devices.
	 * On some desktop systems this function may do nothing.
	 * @param discardcolor Whether to discard the texture(s) of the active Canvas(es) (the contents of the screen if no Canvas is active.)
	 * @param discardstencil Whether to discard the contents of the stencil buffer of the screen / active Canvas.
	 */
	@:overload(function (discardcolors: Table<Dynamic, Dynamic>, ?discardstencil: Bool): Void {})
	public static function discard(?discardcolor: Bool, ?discardstencil: Bool): Void;

	/**
	 * Draws a Drawable object (an Image, Canvas, SpriteBatch, ParticleSystem, Mesh, Text object, or Video) on the screen with optional rotation, scaling and shearing.
	 * Objects are drawn relative to their local coordinate system. The origin is by default located at the top left corner of Image and Canvas. All scaling, shearing, and rotation arguments transform the object relative to that point. Also, the position of the origin can be specified on the screen coordinate system.
	 * It's possible to rotate an object about its center by offsetting the origin to the center. Angles must be given in radians for rotation. One can also use a negative scaling factor to flip about its centerline. 
	 * Note that the offsets are applied before rotation, scaling, or shearing; scaling and shearing are applied before rotation.
	 * The right and bottom edges of the object are shifted at an angle defined by the shearing factors.
	 * When using the default shader anything drawn with this function will be tinted according to the currently selected color.  Set it to pure white to preserve the object's original colors.
	 * @param drawable A drawable object.
	 * @param x The position to draw the object (x-axis).
	 * @param y The position to draw the object (y-axis).
	 * @param r Orientation (radians).
	 * @param sx Scale factor (x-axis).
	 * @param sy Scale factor (y-axis).
	 * @param ox Origin offset (x-axis).
	 * @param oy Origin offset (y-axis).
	 * @param kx Shearing factor (x-axis).
	 * @param ky Shearing factor (y-axis).
	 */
	@:overload(function (texture: Texture, quad: Quad, x: Float, y: Float, ?r: Float, ?sx: Float, ?sy: Float, ?ox: Float, ?oy: Float, ?kx: Float, ?ky: Float): Void {})
	@:overload(function (drawable: Drawable, transform: Transform): Void {})
	@:overload(function (texture: Texture, quad: Quad, transform: Transform): Void {})
	public static function draw(drawable: Drawable, ?x: Float, ?y: Float, ?r: Float, ?sx: Float, ?sy: Float, ?ox: Float, ?oy: Float, ?kx: Float, ?ky: Float): Void;

	/**
	 * Draws many instances of a Mesh with a single draw call, using hardware geometry instancing.
	 * Each instance can have unique properties (positions, colors, etc.) but will not by default unless a custom per-instance vertex attributes or the love_InstanceID GLSL 3 vertex shader variable is used, otherwise they will all render at the same position on top of each other.
	 * Instancing is not supported by some older GPUs that are only capable of using OpenGL ES 2 or OpenGL 2. Use love.graphics.getSupported to check.
	 * @param mesh The mesh to render.
	 * @param instancecount The number of instances to render.
	 * @param x The position to draw the instances (x-axis).
	 * @param y The position to draw the instances (y-axis).
	 * @param r Orientation (radians).
	 * @param sx Scale factor (x-axis).
	 * @param sy Scale factor (y-axis).
	 * @param ox Origin offset (x-axis).
	 * @param oy Origin offset (y-axis).
	 * @param kx Shearing factor (x-axis).
	 * @param ky Shearing factor (y-axis).
	 */
	@:overload(function (mesh: Mesh, instancecount: Float, transform: Transform): Void {})
	public static function drawInstanced(mesh: Mesh, instancecount: Float, ?x: Float, ?y: Float, ?r: Float, ?sx: Float, ?sy: Float, ?ox: Float, ?oy: Float, ?kx: Float, ?ky: Float): Void;

	/**
	 * Draws a layer of an Array Texture.
	 * @param texture The Array Texture to draw.
	 * @param layerindex The index of the layer to use when drawing.
	 * @param x The position to draw the texture (x-axis).
	 * @param y The position to draw the texture (y-axis).
	 * @param r Orientation (radians).
	 * @param sx Scale factor (x-axis).
	 * @param sy Scale factor (y-axis).
	 * @param ox Origin offset (x-axis).
	 * @param oy Origin offset (y-axis).
	 * @param kx Shearing factor (x-axis).
	 * @param ky Shearing factor (y-axis).
	 */
	@:overload(function (texture: Texture, layerindex: Float, quad: Quad, ?x: Float, ?y: Float, ?r: Float, ?sx: Float, ?sy: Float, ?ox: Float, ?oy: Float, ?kx: Float, ?ky: Float): Void {})
	@:overload(function (texture: Texture, layerindex: Float, transform: Transform): Void {})
	@:overload(function (texture: Texture, layerindex: Float, quad: Quad, transform: Transform): Void {})
	public static function drawLayer(texture: Texture, layerindex: Float, ?x: Float, ?y: Float, ?r: Float, ?sx: Float, ?sy: Float, ?ox: Float, ?oy: Float, ?kx: Float, ?ky: Float): Void;

	/**
	 * Draws an ellipse.
	 * @param mode How to draw the ellipse.
	 * @param x The position of the center along x-axis.
	 * @param y The position of the center along y-axis.
	 * @param radiusx The radius of the ellipse along the x-axis (half the ellipse's width).
	 * @param radiusy The radius of the ellipse along the y-axis (half the ellipse's height).
	 */
	@:overload(function (mode: DrawMode, x: Float, y: Float, radiusx: Float, radiusy: Float, segments: Float): Void {})
	public static function ellipse(mode: DrawMode, x: Float, y: Float, radiusx: Float, radiusy: Float): Void;

	/**
	 * Immediately renders any pending automatically batched draws.
	 * LÖVE will call this function internally as needed when most state is changed, so it is not necessary to manually call it.
	 * The current batch will be automatically flushed by love.graphics state changes (except for the transform stack and the current color), as well as Shader:send and methods on Textures which change their state. Using a different Image in consecutive love.graphics.draw calls will also flush the current batch.
	 * SpriteBatches, ParticleSystems, Meshes, and Text objects do their own batching and do not affect automatic batching of other draws, aside from flushing the current batch when they're drawn.
	 */
	public static function flushBatch(): Void;

	/**
	 * Gets the current background color.
	 * In versions prior to 11.0, color component values were within the range of 0 to 255 instead of 0 to 1.
	 */
	public static function getBackgroundColor(): GraphicsModuleGetBackgroundColorResult;

	/**
	 * Gets the blending mode.
	 */
	public static function getBlendMode(): GraphicsModuleGetBlendModeResult;

	/**
	 * Gets the current target Canvas.
	 * @return The Canvas set by setCanvas. Returns nil if drawing to the real screen.
	 */
	public static function getCanvas(): Canvas;

	/**
	 * Gets the available Canvas formats, and whether each is supported.
	 * @return A table containing CanvasFormats as keys, and a boolean indicating whether the format is supported as values. Not all systems support all formats.
	 */
	@:overload(function (readable: Bool): Table<Dynamic, Dynamic> {})
	public static function getCanvasFormats(): Table<Dynamic, Dynamic>;

	/**
	 * Gets the current color.
	 * In versions prior to 11.0, color component values were within the range of 0 to 255 instead of 0 to 1.
	 */
	public static function getColor(): GraphicsModuleGetColorResult;

	/**
	 * Gets the active color components used when drawing. Normally all 4 components are active unless love.graphics.setColorMask has been used.
	 * The color mask determines whether individual components of the colors of drawn objects will affect the color of the screen. They affect love.graphics.clear and Canvas:clear as well.
	 */
	public static function getColorMask(): GraphicsModuleGetColorMaskResult;

	/**
	 * Gets the DPI scale factor of the window.
	 * The DPI scale factor represents relative pixel density. The pixel density inside the window might be greater (or smaller) than the 'size' of the window. For example on a retina screen in Mac OS X with the highdpi window flag enabled, the window may take up the same physical size as an 800x600 window, but the area inside the window uses 1600x1200 pixels. love.graphics.getDPIScale() would return 2 in that case.
	 * The love.window.fromPixels and love.window.toPixels functions can also be used to convert between units.
	 * The highdpi window flag must be enabled to use the full pixel density of a Retina screen on Mac OS X and iOS. The flag currently does nothing on Windows and Linux, and on Android it is effectively always enabled.
	 * @return The pixel scale factor associated with the window.
	 */
	public static function getDPIScale(): Float;

	/**
	 * Returns the default scaling filters used with Images, Canvases, and Fonts.
	 */
	public static function getDefaultFilter(): GraphicsModuleGetDefaultFilterResult;

	/**
	 * Gets the current depth test mode and whether writing to the depth buffer is enabled.
	 * This is low-level functionality designed for use with custom vertex shaders and Meshes with custom vertex attributes. No higher level APIs are provided to set the depth of 2D graphics such as shapes, lines, and Images.
	 */
	public static function getDepthMode(): GraphicsModuleGetDepthModeResult;

	/**
	 * Gets the width and height in pixels of the window.
	 */
	public static function getDimensions(): GraphicsModuleGetDimensionsResult;

	/**
	 * Gets the current Font object.
	 * @return The current Font. Automatically creates and sets the default font, if none is set yet.
	 */
	public static function getFont(): Font;

	/**
	 * Gets whether triangles with clockwise- or counterclockwise-ordered vertices are considered front-facing.
	 * This is designed for use in combination with Mesh face culling. Other love.graphics shapes, lines, and sprites are not guaranteed to have a specific winding order to their internal vertices.
	 * @return The winding mode being used. The default winding is counterclockwise ('ccw').
	 */
	public static function getFrontFaceWinding(): VertexWinding;

	/**
	 * Gets the height in pixels of the window.
	 * @return The height of the window.
	 */
	public static function getHeight(): Float;

	/**
	 * Gets the raw and compressed pixel formats usable for Images, and whether each is supported.
	 * @return A table containing PixelFormats as keys, and a boolean indicating whether the format is supported as values. Not all systems support all formats.
	 */
	public static function getImageFormats(): Table<Dynamic, Dynamic>;

	/**
	 * Gets the line join style.
	 * @return The LineJoin style.
	 */
	public static function getLineJoin(): LineJoin;

	/**
	 * Gets the line style.
	 * @return The current line style.
	 */
	public static function getLineStyle(): LineStyle;

	/**
	 * Gets the current line width.
	 * @return The current line width.
	 */
	public static function getLineWidth(): Float;

	/**
	 * Gets whether back-facing triangles in a Mesh are culled.
	 * Mesh face culling is designed for use with low level custom hardware-accelerated 3D rendering via custom vertex attributes on Meshes, custom vertex shaders, and depth testing with a depth buffer.
	 * @return The Mesh face culling mode in use (whether to render everything, cull back-facing triangles, or cull front-facing triangles).
	 */
	public static function getMeshCullMode(): CullMode;

	/**
	 * Gets the width and height in pixels of the window.
	 * love.graphics.getDimensions gets the dimensions of the window in units scaled by the screen's DPI scale factor, rather than pixels. Use getDimensions for calculations related to drawing to the screen and using the graphics coordinate system (calculating the center of the screen, for example), and getPixelDimensions only when dealing specifically with underlying pixels (pixel-related calculations in a pixel Shader, for example).
	 */
	public static function getPixelDimensions(): GraphicsModuleGetPixelDimensionsResult;

	/**
	 * Gets the height in pixels of the window.
	 * The graphics coordinate system and DPI scale factor, rather than raw pixels. Use getHeight for calculations related to drawing to the screen and using the coordinate system (calculating the center of the screen, for example), and getPixelHeight only when dealing specifically with underlying pixels (pixel-related calculations in a pixel Shader, for example).
	 * @return The height of the window in pixels.
	 */
	public static function getPixelHeight(): Float;

	/**
	 * Gets the width in pixels of the window.
	 * The graphics coordinate system and DPI scale factor, rather than raw pixels. Use getWidth for calculations related to drawing to the screen and using the coordinate system (calculating the center of the screen, for example), and getPixelWidth only when dealing specifically with underlying pixels (pixel-related calculations in a pixel Shader, for example).
	 * @return The width of the window in pixels.
	 */
	public static function getPixelWidth(): Float;

	/**
	 * Gets the point size.
	 * @return The current point size.
	 */
	public static function getPointSize(): Float;

	/**
	 * Gets information about the system's video card and drivers.
	 */
	public static function getRendererInfo(): GraphicsModuleGetRendererInfoResult;

	/**
	 * Gets the current scissor box.
	 */
	public static function getScissor(): GraphicsModuleGetScissorResult;

	/**
	 * Gets the current Shader. Returns nil if none is set.
	 * @return The currently active Shader, or nil if none is set.
	 */
	public static function getShader(): Shader;

	/**
	 * Gets the current depth of the transform / state stack (the number of pushes without corresponding pops).
	 * @return The current depth of the transform and state love.graphics stack.
	 */
	public static function getStackDepth(): Float;

	/**
	 * Gets performance-related rendering statistics. 
	 * @return A table with the following fields:
	 */
	@:overload(function (stats: Table<Dynamic, Dynamic>): Table<Dynamic, Dynamic> {})
	public static function getStats(): Table<Dynamic, Dynamic>;

	/**
	 * Gets the current stencil test configuration.
	 * When stencil testing is enabled, the geometry of everything that is drawn afterward will be clipped / stencilled out based on a comparison between the arguments of this function and the stencil value of each pixel that the geometry touches. The stencil values of pixels are affected via love.graphics.stencil.
	 * Each Canvas has its own per-pixel stencil values.
	 */
	public static function getStencilTest(): GraphicsModuleGetStencilTestResult;

	/**
	 * Gets the optional graphics features and whether they're supported on the system.
	 * Some older or low-end systems don't always support all graphics features.
	 * @return A table containing GraphicsFeature keys, and boolean values indicating whether each feature is supported.
	 */
	public static function getSupported(): Table<Dynamic, Dynamic>;

	/**
	 * Gets the system-dependent maximum values for love.graphics features.
	 * @return A table containing GraphicsLimit keys, and number values.
	 */
	public static function getSystemLimits(): Table<Dynamic, Dynamic>;

	/**
	 * Gets the available texture types, and whether each is supported.
	 * @return A table containing TextureTypes as keys, and a boolean indicating whether the type is supported as values. Not all systems support all types.
	 */
	public static function getTextureTypes(): Table<Dynamic, Dynamic>;

	/**
	 * Gets the width in pixels of the window.
	 * @return The width of the window.
	 */
	public static function getWidth(): Float;

	/**
	 * Sets the scissor to the rectangle created by the intersection of the specified rectangle with the existing scissor.  If no scissor is active yet, it behaves like love.graphics.setScissor.
	 * The scissor limits the drawing area to a specified rectangle. This affects all graphics calls, including love.graphics.clear.
	 * The dimensions of the scissor is unaffected by graphical transformations (translate, scale, ...).
	 * @param x The x-coordinate of the upper left corner of the rectangle to intersect with the existing scissor rectangle.
	 * @param y The y-coordinate of the upper left corner of the rectangle to intersect with the existing scissor rectangle.
	 * @param width The width of the rectangle to intersect with the existing scissor rectangle.
	 * @param height The height of the rectangle to intersect with the existing scissor rectangle.
	 */
	public static function intersectScissor(x: Float, y: Float, width: Float, height: Float): Void;

	/**
	 * Converts the given 2D position from screen-space into global coordinates.
	 * This effectively applies the reverse of the current graphics transformations to the given position. A similar Transform:inverseTransformPoint method exists for Transform objects.
	 * @param screenX The x component of the screen-space position.
	 * @param screenY The y component of the screen-space position.
	 */
	public static function inverseTransformPoint(screenX: Float, screenY: Float): GraphicsModuleInverseTransformPointResult;

	/**
	 * Gets whether the graphics module is able to be used. If it is not active, love.graphics function and method calls will not work correctly and may cause the program to crash.
	 * The graphics module is inactive if a window is not open, or if the app is in the background on iOS. Typically the app's execution will be automatically paused by the system, in the latter case.
	 * @return Whether the graphics module is active and able to be used.
	 */
	public static function isActive(): Bool;

	/**
	 * Gets whether gamma-correct rendering is supported and enabled. It can be enabled by setting t.gammacorrect = true in love.conf.
	 * Not all devices support gamma-correct rendering, in which case it will be automatically disabled and this function will return false. It is supported on desktop systems which have graphics cards that are capable of using OpenGL 3 / DirectX 10, and iOS devices that can use OpenGL ES 3.
	 * @return True if gamma-correct rendering is supported and was enabled in love.conf, false otherwise.
	 */
	public static function isGammaCorrect(): Bool;

	/**
	 * Gets whether wireframe mode is used when drawing.
	 * @return True if wireframe lines are used when drawing, false if it's not.
	 */
	public static function isWireframe(): Bool;

	/**
	 * Draws lines between points.
	 * @param x1 The position of first point on the x-axis.
	 * @param y1 The position of first point on the y-axis.
	 * @param x2 The position of second point on the x-axis.
	 * @param y2 The position of second point on the y-axis.
	 * @param ... You can continue passing point positions to draw a polyline.
	 */
	@:overload(function (points: Table<Dynamic, Dynamic>): Void {})
	public static function line(x1: Float, y1: Float, x2: Float, y2: Float, args: Rest<Float>): Void;

	/**
	 * Creates a new array Image.
	 * An array image / array texture is a single object which contains multiple 'layers' or 'slices' of 2D sub-images. It can be thought of similarly to a texture atlas or sprite sheet, but it doesn't suffer from the same tile / quad bleeding artifacts that texture atlases do – although every sub-image must have the same dimensions.
	 * A specific layer of an array image can be drawn with love.graphics.drawLayer / SpriteBatch:addLayer, or with the Quad variant of love.graphics.draw and Quad:setLayer, or via a custom Shader.
	 * To use an array image in a Shader, it must be declared as a ArrayImage or sampler2DArray type (instead of Image or sampler2D). The Texel(ArrayImage image, vec3 texturecoord) shader function must be used to get pixel colors from a slice of the array image. The vec3 argument contains the texture coordinate in the first two components, and the 0-based slice index in the third component.
	 * @param slices A table containing filepaths to images (or File, FileData, ImageData, or CompressedImageData objects), in an array. Each sub-image must have the same dimensions. A table of tables can also be given, where each sub-table contains all mipmap levels for the slice index of that sub-table.
	 * @param settings Optional table of settings to configure the array image, containing the following fields:
	 * @return An Array Image object.
	 */
	public static function newArrayImage(slices: Table<Dynamic, Dynamic>, ?settings: Table<Dynamic, Dynamic>): Image;

	/**
	 * Creates a new Canvas object for offscreen rendering.
	 * @return A new Canvas with dimensions equal to the window's size in pixels.
	 */
	@:overload(function (width: Float, height: Float): Canvas {})
	@:overload(function (width: Float, height: Float, ?settings: Table<Dynamic, Dynamic>): Canvas {})
	@:overload(function (width: Float, height: Float, layers: Float, ?settings: Table<Dynamic, Dynamic>): Canvas {})
	public static function newCanvas(): Canvas;

	/**
	 * Creates a new cubemap Image.
	 * Cubemap images have 6 faces (sides) which represent a cube. They can't be rendered directly, they can only be used in Shader code (and sent to the shader via Shader:send).
	 * To use a cubemap image in a Shader, it must be declared as a CubeImage or samplerCube type (instead of Image or sampler2D). The Texel(CubeImage image, vec3 direction) shader function must be used to get pixel colors from the cubemap. The vec3 argument is a normalized direction from the center of the cube, rather than explicit texture coordinates.
	 * Each face in a cubemap image must have square dimensions.
	 * For variants of this function which accept a single image containing multiple cubemap faces, they must be laid out in one of the following forms in the image:
	 *    +y
	 * +z +x -z
	 *    -y
	 *    -x
	 * or:
	 *    +y
	 * -x +z +x -z
	 *    -y
	 * or:
	 * +x
	 * -x
	 * +y
	 * -y
	 * +z
	 * -z
	 * or:
	 * +x -x +y -y +z -z
	 * @param filename The filepath to a cubemap image file (or a File, FileData, or ImageData).
	 * @param settings Optional table of settings to configure the cubemap image, containing the following fields:
	 * @return An cubemap Image object.
	 */
	@:overload(function (faces: Table<Dynamic, Dynamic>, ?settings: Table<Dynamic, Dynamic>): Image {})
	public static function newCubeImage(filename: String, ?settings: Table<Dynamic, Dynamic>): Image;

	/**
	 * Creates a new Font from a TrueType Font or BMFont file. Created fonts are not cached, in that calling this function with the same arguments will always create a new Font object.
	 * All variants which accept a filename can also accept a Data object instead.
	 * @param filename The filepath to the BMFont or TrueType font file.
	 * @return A Font object which can be used to draw text on screen.
	 */
	@:overload(function (filename: String, size: Float, ?hinting: HintingMode, ?dpiscale: Float): Font {})
	@:overload(function (filename: String, imagefilename: String): Font {})
	@:overload(function (?size: Float, ?hinting: HintingMode, ?dpiscale: Float): Font {})
	public static function newFont(filename: String): Font;

	/**
	 * Creates a new Image from a filepath, FileData, an ImageData, or a CompressedImageData, and optionally generates or specifies mipmaps for the image.
	 * @param filename The filepath to the image file.
	 * @param settings A table containing the following fields:
	 * @return A new Image object which can be drawn on screen.
	 */
	@:overload(function (fileData: FileData, ?settings: Table<Dynamic, Dynamic>): Image {})
	@:overload(function (imageData: ImageData, ?settings: Table<Dynamic, Dynamic>): Image {})
	@:overload(function (compressedImageData: CompressedImageData, ?settings: Table<Dynamic, Dynamic>): Image {})
	public static function newImage(filename: String, ?settings: Table<Dynamic, Dynamic>): Image;

	/**
	 * Creates a new specifically formatted image.
	 * In versions prior to 0.9.0, LÖVE expects ISO 8859-1 encoding for the glyphs string.
	 * @param filename The filepath to the image file.
	 * @param glyphs A string of the characters in the image in order from left to right.
	 * @return A Font object which can be used to draw text on screen.
	 */
	@:overload(function (imageData: ImageData, glyphs: String): Font {})
	@:overload(function (filename: String, glyphs: String, extraspacing: Float): Font {})
	public static function newImageFont(filename: String, glyphs: String): Font;

	/**
	 * Creates a new Mesh.
	 * Use Mesh:setTexture if the Mesh should be textured with an Image or Canvas when it's drawn.
	 * In versions prior to 11.0, color and byte component values were within the range of 0 to 255 instead of 0 to 1.
	 * @param vertices The table filled with vertex information tables for each vertex as follows:
	 * @param mode How the vertices are used when drawing. The default mode 'fan' is sufficient for simple convex polygons.
	 * @param usage The expected usage of the Mesh. The specified usage mode affects the Mesh's memory usage and performance.
	 * @return The new mesh.
	 */
	@:overload(function (vertexcount: Float, ?mode: MeshDrawMode, ?usage: SpriteBatchUsage): Mesh {})
	@:overload(function (vertexformat: Table<Dynamic, Dynamic>, vertices: Table<Dynamic, Dynamic>, ?mode: MeshDrawMode, ?usage: SpriteBatchUsage): Mesh {})
	@:overload(function (vertexformat: Table<Dynamic, Dynamic>, vertexcount: Float, ?mode: MeshDrawMode, ?usage: SpriteBatchUsage): Mesh {})
	@:overload(function (vertexcount: Float, ?texture: Texture, ?mode: MeshDrawMode): Mesh {})
	public static function newMesh(vertices: Table<Dynamic, Dynamic>, ?mode: MeshDrawMode, ?usage: SpriteBatchUsage): Mesh;

	/**
	 * Creates a new ParticleSystem.
	 * @param image The image to use.
	 * @param buffer The max number of particles at the same time.
	 * @return A new ParticleSystem.
	 */
	@:overload(function (texture: Texture, ?buffer: Float): ParticleSystem {})
	public static function newParticleSystem(image: Image, ?buffer: Float): ParticleSystem;

	/**
	 * Creates a new Quad.
	 * The purpose of a Quad is to use a fraction of an image to draw objects, as opposed to drawing entire image. It is most useful for sprite sheets and atlases: in a sprite atlas, multiple sprites reside in same image, quad is used to draw a specific sprite from that image; in animated sprites with all frames residing in the same image, quad is used to draw specific frame from the animation.
	 * @param x The top-left position in the Image along the x-axis.
	 * @param y The top-left position in the Image along the y-axis.
	 * @param width The width of the Quad in the Image. (Must be greater than 0.)
	 * @param height The height of the Quad in the Image. (Must be greater than 0.)
	 * @param sw The reference width, the width of the Image. (Must be greater than 0.)
	 * @param sh The reference height, the height of the Image. (Must be greater than 0.)
	 * @return The new Quad.
	 */
	@:overload(function (x: Float, y: Float, width: Float, height: Float, texture: Texture): Quad {})
	public static function newQuad(x: Float, y: Float, width: Float, height: Float, sw: Float, sh: Float): Quad;

	/**
	 * Creates a new Shader object for hardware-accelerated vertex and pixel effects. A Shader contains either vertex shader code, pixel shader code, or both.
	 * Shaders are small programs which are run on the graphics card when drawing. Vertex shaders are run once for each vertex (for example, an image has 4 vertices - one at each corner. A Mesh might have many more.) Pixel shaders are run once for each pixel on the screen which the drawn object touches. Pixel shader code is executed after all the object's vertices have been processed by the vertex shader.
	 * @param code The pixel shader or vertex shader code, or a filename pointing to a file with the code.
	 * @return A Shader object for use in drawing operations.
	 */
	@:overload(function (pixelcode: String, vertexcode: String): Shader {})
	public static function newShader(code: String): Shader;

	/**
	 * Creates a new SpriteBatch object.
	 * @param image The Image to use for the sprites.
	 * @param maxsprites The maximum number of sprites that the SpriteBatch can contain at any given time. Since version 11.0, additional sprites added past this number will automatically grow the spritebatch.
	 * @return The new SpriteBatch.
	 */
	@:overload(function (image: Image, ?maxsprites: Float, ?usage: SpriteBatchUsage): SpriteBatch {})
	@:overload(function (texture: Texture, ?maxsprites: Float, ?usage: SpriteBatchUsage): SpriteBatch {})
	public static function newSpriteBatch(image: Image, ?maxsprites: Float): SpriteBatch;

	/**
	 * Creates a new drawable Text object.
	 * @param font The font to use for the text.
	 * @param textstring The initial string of text that the new Text object will contain. May be nil.
	 * @return The new drawable Text object.
	 */
	@:overload(function (font: Font, coloredtext: Table<Dynamic, Dynamic>): Text {})
	public static function newText(font: Font, ?textstring: String): Text;

	/**
	 * Creates a new drawable Video. Currently only Ogg Theora video files are supported.
	 * @param filename The file path to the Ogg Theora video file.
	 * @return A new Video.
	 */
	@:overload(function (videostream: VideoStream): Video {})
	@:overload(function (filename: String, ?settings: Table<Dynamic, Dynamic>): Video {})
	@:overload(function (filename: String, ?loadaudio: Bool): Video {})
	@:overload(function (videostream: VideoStream, ?loadaudio: Bool): Video {})
	public static function newVideo(filename: String): Video;

	/**
	 * Creates a new volume (3D) Image.
	 * Volume images are 3D textures with width, height, and depth. They can't be rendered directly, they can only be used in Shader code (and sent to the shader via Shader:send).
	 * To use a volume image in a Shader, it must be declared as a VolumeImage or sampler3D type (instead of Image or sampler2D). The Texel(VolumeImage image, vec3 texcoords) shader function must be used to get pixel colors from the volume image. The vec3 argument is a normalized texture coordinate with the z component representing the depth to sample at (ranging from 1).
	 * Volume images are typically used as lookup tables in shaders for color grading, for example, because sampling using a texture coordinate that is partway in between two pixels can interpolate across all 3 dimensions in the volume image, resulting in a smooth gradient even when a small-sized volume image is used as the lookup table.
	 * Array images are a much better choice than volume images for storing multiple different sprites in a single array image for directly drawing them.
	 * @param layers A table containing filepaths to images (or File, FileData, ImageData, or CompressedImageData objects), in an array. A table of tables can also be given, where each sub-table represents a single mipmap level and contains all layers for that mipmap.
	 * @param settings Optional table of settings to configure the volume image, containing the following fields:
	 * @return A volume Image object.
	 */
	public static function newVolumeImage(layers: Table<Dynamic, Dynamic>, ?settings: Table<Dynamic, Dynamic>): Image;

	/**
	 * Resets the current coordinate transformation.
	 * This function is always used to reverse any previous calls to love.graphics.rotate, love.graphics.scale, love.graphics.shear or love.graphics.translate. It returns the current transformation state to its defaults.
	 */
	public static function origin(): Void;

	/**
	 * Draws one or more points.
	 * @param x The position of the first point on the x-axis.
	 * @param y The position of the first point on the y-axis.
	 * @param ... The x and y coordinates of additional points.
	 */
	@:overload(function (points: Table<Dynamic, Dynamic>): Void {})
	@:overload(function (points: Table<Dynamic, Dynamic>): Void {})
	public static function points(x: Float, y: Float, args: Rest<Float>): Void;

	/**
	 * Draw a polygon.
	 * Following the mode argument, this function can accept multiple numeric arguments or a single table of numeric arguments. In either case the arguments are interpreted as alternating x and y coordinates of the polygon's vertices.
	 * @param mode How to draw the polygon.
	 * @param ... The vertices of the polygon.
	 */
	@:overload(function (mode: DrawMode, vertices: Table<Dynamic, Dynamic>): Void {})
	public static function polygon(mode: DrawMode, args: Rest<Float>): Void;

	/**
	 * Pops the current coordinate transformation from the transformation stack.
	 * This function is always used to reverse a previous push operation. It returns the current transformation state to what it was before the last preceding push.
	 */
	public static function pop(): Void;

	/**
	 * Displays the results of drawing operations on the screen.
	 * This function is used when writing your own love.run function. It presents all the results of your drawing operations on the screen. See the example in love.run for a typical use of this function.
	 */
	public static function present(): Void;

	/**
	 * Draws text on screen. If no Font is set, one will be created and set (once) if needed.
	 * As of LOVE 0.7.1, when using translation and scaling functions while drawing text, this function assumes the scale occurs first.  If you don't script with this in mind, the text won't be in the right position, or possibly even on screen.
	 * love.graphics.print and love.graphics.printf both support UTF-8 encoding. You'll also need a proper Font for special characters.
	 * In versions prior to 11.0, color and byte component values were within the range of 0 to 255 instead of 0 to 1.
	 * @param text The text to draw.
	 * @param x The position to draw the object (x-axis).
	 * @param y The position to draw the object (y-axis).
	 * @param r Orientation (radians).
	 * @param sx Scale factor (x-axis).
	 * @param sy Scale factor (y-axis).
	 * @param ox Origin offset (x-axis).
	 * @param oy Origin offset (y-axis).
	 * @param kx Shearing factor (x-axis).
	 * @param ky Shearing factor (y-axis).
	 */
	@:overload(function (coloredtext: Table<Dynamic, Dynamic>, ?x: Float, ?y: Float, ?angle: Float, ?sx: Float, ?sy: Float, ?ox: Float, ?oy: Float, ?kx: Float, ?ky: Float): Void {})
	@:overload(function (text: String, transform: Transform): Void {})
	@:overload(function (coloredtext: Table<Dynamic, Dynamic>, transform: Transform): Void {})
	@:overload(function (text: String, font: Font, transform: Transform): Void {})
	@:overload(function (coloredtext: Table<Dynamic, Dynamic>, font: Font, transform: Transform): Void {})
	public static function print(text: String, ?x: Float, ?y: Float, ?r: Float, ?sx: Float, ?sy: Float, ?ox: Float, ?oy: Float, ?kx: Float, ?ky: Float): Void;

	/**
	 * Draws formatted text, with word wrap and alignment.
	 * See additional notes in love.graphics.print.
	 * The word wrap limit is applied before any scaling, rotation, and other coordinate transformations. Therefore the amount of text per line stays constant given the same wrap limit, even if the scale arguments change.
	 * In version 0.9.2 and earlier, wrapping was implemented by breaking up words by spaces and putting them back together to make sure things fit nicely within the limit provided. However, due to the way this is done, extra spaces between words would end up missing when printed on the screen, and some lines could overflow past the provided wrap limit. In version 0.10.0 and newer this is no longer the case.
	 * In versions prior to 11.0, color and byte component values were within the range of 0 to 255 instead of 0 to 1.
	 * @param text A text string.
	 * @param x The position on the x-axis.
	 * @param y The position on the y-axis.
	 * @param limit Wrap the line after this many horizontal pixels.
	 * @param align The alignment.
	 * @param r Orientation (radians).
	 * @param sx Scale factor (x-axis).
	 * @param sy Scale factor (y-axis).
	 * @param ox Origin offset (x-axis).
	 * @param oy Origin offset (y-axis).
	 * @param kx Shearing factor (x-axis).
	 * @param ky Shearing factor (y-axis).
	 */
	@:overload(function (text: String, font: Font, x: Float, y: Float, limit: Float, ?align: AlignMode, ?r: Float, ?sx: Float, ?sy: Float, ?ox: Float, ?oy: Float, ?kx: Float, ?ky: Float): Void {})
	@:overload(function (text: String, transform: Transform, limit: Float, ?align: AlignMode): Void {})
	@:overload(function (text: String, font: Font, transform: Transform, limit: Float, ?align: AlignMode): Void {})
	@:overload(function (coloredtext: Table<Dynamic, Dynamic>, x: Float, y: Float, limit: Float, align: AlignMode, ?angle: Float, ?sx: Float, ?sy: Float, ?ox: Float, ?oy: Float, ?kx: Float, ?ky: Float): Void {})
	@:overload(function (coloredtext: Table<Dynamic, Dynamic>, font: Font, x: Float, y: Float, limit: Float, ?align: AlignMode, ?angle: Float, ?sx: Float, ?sy: Float, ?ox: Float, ?oy: Float, ?kx: Float, ?ky: Float): Void {})
	@:overload(function (coloredtext: Table<Dynamic, Dynamic>, transform: Transform, limit: Float, ?align: AlignMode): Void {})
	@:overload(function (coloredtext: Table<Dynamic, Dynamic>, font: Font, transform: Transform, limit: Float, ?align: AlignMode): Void {})
	public static function printf(text: String, x: Float, y: Float, limit: Float, ?align: AlignMode, ?r: Float, ?sx: Float, ?sy: Float, ?ox: Float, ?oy: Float, ?kx: Float, ?ky: Float): Void;

	/**
	 * Copies and pushes the current coordinate transformation to the transformation stack.
	 * This function is always used to prepare for a corresponding pop operation later. It stores the current coordinate transformation state into the transformation stack and keeps it active. Later changes to the transformation can be undone by using the pop operation, which returns the coordinate transform to the state it was in before calling push.
	 */
	@:overload(function (stack: StackType): Void {})
	public static function push(): Void;

	/**
	 * Draws a rectangle.
	 * @param mode How to draw the rectangle.
	 * @param x The position of top-left corner along the x-axis.
	 * @param y The position of top-left corner along the y-axis.
	 * @param width Width of the rectangle.
	 * @param height Height of the rectangle.
	 */
	@:overload(function (mode: DrawMode, x: Float, y: Float, width: Float, height: Float, rx: Float, ?ry: Float, ?segments: Float): Void {})
	public static function rectangle(mode: DrawMode, x: Float, y: Float, width: Float, height: Float): Void;

	/**
	 * Replaces the current coordinate transformation with the given Transform object.
	 * @param transform The Transform object to replace the current graphics coordinate transform with.
	 */
	public static function replaceTransform(transform: Transform): Void;

	/**
	 * Resets the current graphics settings.
	 * Calling reset makes the current drawing color white, the current background color black, disables any active color component masks, disables wireframe mode and resets the current graphics transformation to the origin. It also sets both the point and line drawing modes to smooth and their sizes to 1.0.
	 */
	public static function reset(): Void;

	/**
	 * Rotates the coordinate system in two dimensions.
	 * Calling this function affects all future drawing operations by rotating the coordinate system around the origin by the given amount of radians. This change lasts until love.draw() exits.
	 * @param angle The amount to rotate the coordinate system in radians.
	 */
	public static function rotate(angle: Float): Void;

	/**
	 * Scales the coordinate system in two dimensions.
	 * By default the coordinate system in LÖVE corresponds to the display pixels in horizontal and vertical directions one-to-one, and the x-axis increases towards the right while the y-axis increases downwards. Scaling the coordinate system changes this relation.
	 * After scaling by sx and sy, all coordinates are treated as if they were multiplied by sx and sy. Every result of a drawing operation is also correspondingly scaled, so scaling by (2, 2) for example would mean making everything twice as large in both x- and y-directions. Scaling by a negative value flips the coordinate system in the corresponding direction, which also means everything will be drawn flipped or upside down, or both. Scaling by zero is not a useful operation.
	 * Scale and translate are not commutative operations, therefore, calling them in different orders will change the outcome.
	 * Scaling lasts until love.draw() exits.
	 * @param sx The scaling in the direction of the x-axis.
	 * @param sy The scaling in the direction of the y-axis. If omitted, it defaults to same as parameter sx.
	 */
	public static function scale(sx: Float, ?sy: Float): Void;

	/**
	 * Sets the background color.
	 * @param red The red component (0-1).
	 * @param green The green component (0-1).
	 * @param blue The blue component (0-1).
	 * @param alpha The alpha component (0-1).
	 */
	@:overload(function (rgba: Table<Dynamic, Dynamic>): Void {})
	public static function setBackgroundColor(red: Float, green: Float, blue: Float, ?alpha: Float): Void;

	/**
	 * Sets the blending mode.
	 * @param mode The blend mode to use.
	 */
	@:overload(function (mode: BlendMode, ?alphamode: BlendAlphaMode): Void {})
	public static function setBlendMode(mode: BlendMode): Void;

	/**
	 * Captures drawing operations to a Canvas.
	 * @param canvas The new target.
	 * @param mipmap The mipmap level to render to, for Canvases with mipmaps.
	 */
	@:overload(function (): Void {})
	@:overload(function (canvas1: Canvas, canvas2: Canvas, args: Rest<Canvas>): Void {})
	@:overload(function (canvas: Canvas, slice: Float, ?mipmap: Float): Void {})
	@:overload(function (setup: Table<Dynamic, Dynamic>): Void {})
	public static function setCanvas(canvas: Canvas, ?mipmap: Float): Void;

	/**
	 * Sets the color used for drawing.
	 * In versions prior to 11.0, color component values were within the range of 0 to 255 instead of 0 to 1.
	 * @param red The amount of red.
	 * @param green The amount of green.
	 * @param blue The amount of blue.
	 * @param alpha The amount of alpha.  The alpha value will be applied to all subsequent draw operations, even the drawing of an image.
	 */
	@:overload(function (rgba: Table<Dynamic, Dynamic>): Void {})
	public static function setColor(red: Float, green: Float, blue: Float, ?alpha: Float): Void;

	/**
	 * Sets the color mask. Enables or disables specific color components when rendering and clearing the screen. For example, if '''red''' is set to '''false''', no further changes will be made to the red component of any pixels.
	 * @param red Render red component.
	 * @param green Render green component.
	 * @param blue Render blue component.
	 * @param alpha Render alpha component.
	 */
	@:overload(function (): Void {})
	public static function setColorMask(red: Bool, green: Bool, blue: Bool, alpha: Bool): Void;

	/**
	 * Sets the default scaling filters used with Images, Canvases, and Fonts.
	 * @param min Filter mode used when scaling the image down.
	 * @param mag Filter mode used when scaling the image up.
	 * @param anisotropy Maximum amount of Anisotropic Filtering used.
	 */
	public static function setDefaultFilter(min: FilterMode, ?mag: FilterMode, ?anisotropy: Float): Void;

	/**
	 * Configures depth testing and writing to the depth buffer.
	 * This is low-level functionality designed for use with custom vertex shaders and Meshes with custom vertex attributes. No higher level APIs are provided to set the depth of 2D graphics such as shapes, lines, and Images.
	 * @param comparemode Depth comparison mode used for depth testing.
	 * @param write Whether to write update / write values to the depth buffer when rendering.
	 */
	@:overload(function (): Void {})
	public static function setDepthMode(comparemode: CompareMode, write: Bool): Void;

	/**
	 * Set an already-loaded Font as the current font or create and load a new one from the file and size.
	 * It's recommended that Font objects are created with love.graphics.newFont in the loading stage and then passed to this function in the drawing stage.
	 * @param font The Font object to use.
	 */
	public static function setFont(font: Font): Void;

	/**
	 * Sets whether triangles with clockwise- or counterclockwise-ordered vertices are considered front-facing.
	 * This is designed for use in combination with Mesh face culling. Other love.graphics shapes, lines, and sprites are not guaranteed to have a specific winding order to their internal vertices.
	 * @param winding The winding mode to use. The default winding is counterclockwise ('ccw').
	 */
	public static function setFrontFaceWinding(winding: VertexWinding): Void;

	/**
	 * Sets the line join style. See LineJoin for the possible options.
	 * @param join The LineJoin to use.
	 */
	public static function setLineJoin(join: LineJoin): Void;

	/**
	 * Sets the line style.
	 * @param style The LineStyle to use. Line styles include smooth and rough.
	 */
	public static function setLineStyle(style: LineStyle): Void;

	/**
	 * Sets the line width.
	 * @param width The width of the line.
	 */
	public static function setLineWidth(width: Float): Void;

	/**
	 * Sets whether back-facing triangles in a Mesh are culled.
	 * This is designed for use with low level custom hardware-accelerated 3D rendering via custom vertex attributes on Meshes, custom vertex shaders, and depth testing with a depth buffer.
	 * By default, both front- and back-facing triangles in Meshes are rendered.
	 * @param mode The Mesh face culling mode to use (whether to render everything, cull back-facing triangles, or cull front-facing triangles).
	 */
	public static function setMeshCullMode(mode: CullMode): Void;

	/**
	 * Creates and sets a new Font.
	 * @param size The size of the font.
	 * @return The new font.
	 */
	@:overload(function (filename: String, ?size: Float): Font {})
	@:overload(function (file: File, ?size: Float): Font {})
	@:overload(function (data: Data, ?size: Float): Font {})
	@:overload(function (rasterizer: Rasterizer): Font {})
	public static function setNewFont(?size: Float): Font;

	/**
	 * Sets the point size.
	 * @param size The new point size.
	 */
	public static function setPointSize(size: Float): Void;

	/**
	 * Sets or disables scissor.
	 * The scissor limits the drawing area to a specified rectangle. This affects all graphics calls, including love.graphics.clear. 
	 * The dimensions of the scissor is unaffected by graphical transformations (translate, scale, ...).
	 * @param x x coordinate of upper left corner.
	 * @param y y coordinate of upper left corner.
	 * @param width width of clipping rectangle.
	 * @param height height of clipping rectangle.
	 */
	@:overload(function (): Void {})
	public static function setScissor(x: Float, y: Float, width: Float, height: Float): Void;

	/**
	 * Sets or resets a Shader as the current pixel effect or vertex shaders. All drawing operations until the next ''love.graphics.setShader'' will be drawn using the Shader object specified.
	 * @param shader The new shader.
	 */
	@:overload(function (): Void {})
	public static function setShader(shader: Shader): Void;

	/**
	 * Configures or disables stencil testing.
	 * When stencil testing is enabled, the geometry of everything that is drawn afterward will be clipped / stencilled out based on a comparison between the arguments of this function and the stencil value of each pixel that the geometry touches. The stencil values of pixels are affected via love.graphics.stencil.
	 * @param comparemode The type of comparison to make for each pixel.
	 * @param comparevalue The value to use when comparing with the stencil value of each pixel. Must be between 0 and 255.
	 */
	@:overload(function (): Void {})
	public static function setStencilTest(comparemode: CompareMode, comparevalue: Float): Void;

	/**
	 * Sets whether wireframe lines will be used when drawing.
	 * @param enable True to enable wireframe mode when drawing, false to disable it.
	 */
	public static function setWireframe(enable: Bool): Void;

	/**
	 * Shears the coordinate system.
	 * @param kx The shear factor on the x-axis.
	 * @param ky The shear factor on the y-axis.
	 */
	public static function shear(kx: Float, ky: Float): Void;

	/**
	 * Draws geometry as a stencil.
	 * The geometry drawn by the supplied function sets invisible stencil values of pixels, instead of setting pixel colors. The stencil buffer (which contains those stencil values) can act like a mask / stencil - love.graphics.setStencilTest can be used afterward to determine how further rendering is affected by the stencil values in each pixel.
	 * Stencil values are integers within the range of 255.
	 * @param stencilfunction Function which draws geometry. The stencil values of pixels, rather than the color of each pixel, will be affected by the geometry.
	 * @param action How to modify any stencil values of pixels that are touched by what's drawn in the stencil function.
	 * @param value The new stencil value to use for pixels if the 'replace' stencil action is used. Has no effect with other stencil actions. Must be between 0 and 255.
	 * @param keepvalues True to preserve old stencil values of pixels, false to re-set every pixel's stencil value to 0 before executing the stencil function. love.graphics.clear will also re-set all stencil values.
	 */
	public static function stencil(stencilfunction: Void -> Void, ?action: StencilAction, ?value: Float, ?keepvalues: Bool): Void;

	/**
	 * Converts the given 2D position from global coordinates into screen-space.
	 * This effectively applies the current graphics transformations to the given position. A similar Transform:transformPoint method exists for Transform objects.
	 * @param globalX The x component of the position in global coordinates.
	 * @param globalY The y component of the position in global coordinates.
	 */
	public static function transformPoint(globalX: Float, globalY: Float): GraphicsModuleTransformPointResult;

	/**
	 * Translates the coordinate system in two dimensions.
	 * When this function is called with two numbers, dx, and dy, all the following drawing operations take effect as if their x and y coordinates were x+dx and y+dy. 
	 * Scale and translate are not commutative operations, therefore, calling them in different orders will change the outcome.
	 * This change lasts until love.draw() exits or else a love.graphics.pop reverts to a previous love.graphics.push.
	 * Translating using whole numbers will prevent tearing/blurring of images and fonts draw after translating.
	 * @param dx The translation relative to the x-axis.
	 * @param dy The translation relative to the y-axis.
	 */
	public static function translate(dx: Float, dy: Float): Void;

	/**
	 * Validates shader code. Check if specified shader code does not contain any errors.
	 * @param gles Validate code as GLSL ES shader.
	 * @param code The pixel shader or vertex shader code, or a filename pointing to a file with the code.
	 */
	@:overload(function (gles: Bool, pixelcode: String, vertexcode: String): GraphicsModuleValidateShaderResult {})
	public static function validateShader(gles: Bool, code: String): GraphicsModuleValidateShaderResult;
}

@:multiReturn
extern class GraphicsModuleValidateShaderResult {
	var status: Bool;
	var message: String;
}

@:multiReturn
extern class GraphicsModuleTransformPointResult {
	var screenX: Float;
	var screenY: Float;
}

@:multiReturn
extern class GraphicsModuleInverseTransformPointResult {
	var globalX: Float;
	var globalY: Float;
}

@:multiReturn
extern class GraphicsModuleGetStencilTestResult {
	var comparemode: CompareMode;
	var comparevalue: Float;
}

@:multiReturn
extern class GraphicsModuleGetScissorResult {
	var x: Float;
	var y: Float;
	var width: Float;
	var height: Float;
}

@:multiReturn
extern class GraphicsModuleGetRendererInfoResult {
	var name: String;
	var version: String;
	var vendor: String;
	var device: String;
}

@:multiReturn
extern class GraphicsModuleGetPixelDimensionsResult {
	var pixelwidth: Float;
	var pixelheight: Float;
}

@:multiReturn
extern class GraphicsModuleGetDimensionsResult {
	var width: Float;
	var height: Float;
}

@:multiReturn
extern class GraphicsModuleGetDepthModeResult {
	var comparemode: CompareMode;
	var write: Bool;
}

@:multiReturn
extern class GraphicsModuleGetDefaultFilterResult {
	var min: FilterMode;
	var mag: FilterMode;
	var anisotropy: Float;
}

@:multiReturn
extern class GraphicsModuleGetColorMaskResult {
	var r: Bool;
	var g: Bool;
	var b: Bool;
	var a: Bool;
}

@:multiReturn
extern class GraphicsModuleGetColorResult {
	var r: Float;
	var g: Float;
	var b: Float;
	var a: Float;
}

@:multiReturn
extern class GraphicsModuleGetBlendModeResult {
	var mode: BlendMode;
	var alphamode: BlendAlphaMode;
}

@:multiReturn
extern class GraphicsModuleGetBackgroundColorResult {
	var r: Float;
	var g: Float;
	var b: Float;
	var a: Float;
}