// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.graphics;

/**
 * Types of system-dependent graphics limits checked for using love.graphics.getSystemLimits.
 */
enum abstract GraphicsLimit (String) {

	/**
	 * The maximum size of points.
	 */
	var Pointsize = 'pointsize';

	/**
	 * The maximum width or height of Images and Canvases.
	 */
	var Texturesize = 'texturesize';

	/**
	 * The maximum number of simultaneously active canvases (via love.graphics.setCanvas.)
	 */
	var Multicanvas = 'multicanvas';

	/**
	 * The maximum number of antialiasing samples for a Canvas.
	 */
	var Canvasmsaa = 'canvasmsaa';

	/**
	 * The maximum number of layers in an Array texture.
	 */
	var Texturelayers = 'texturelayers';

	/**
	 * The maximum width, height, or depth of a Volume texture.
	 */
	var Volumetexturesize = 'volumetexturesize';

	/**
	 * The maximum width or height of a Cubemap texture.
	 */
	var Cubetexturesize = 'cubetexturesize';

	/**
	 * The maximum amount of anisotropic filtering. Texture:setMipmapFilter internally clamps the given anisotropy value to the system's limit.
	 */
	var Anisotropy = 'anisotropy';
}