// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.graphics;

/**
 * Graphics features that can be checked for with love.graphics.getSupported.
 */
enum abstract GraphicsFeature (String) {

	/**
	 * Whether the "clampzero" WrapMode is supported.
	 */
	var Clampzero = 'clampzero';

	/**
	 * Whether the "lighten" and "darken" BlendModes are supported.
	 */
	var Lighten = 'lighten';

	/**
	 * Whether multiple formats can be used in the same love.graphics.setCanvas call.
	 */
	var Multicanvasformats = 'multicanvasformats';

	/**
	 * Whether GLSL 3 Shaders can be used.
	 */
	var Glsl3 = 'glsl3';

	/**
	 * Whether mesh instancing is supported.
	 */
	var Instancing = 'instancing';

	/**
	 * Whether textures with non-power-of-two dimensions can use mipmapping and the 'repeat' WrapMode.
	 */
	var Fullnpot = 'fullnpot';

	/**
	 * Whether pixel shaders can use "highp" 32 bit floating point numbers (as opposed to just 16 bit or lower precision).
	 */
	var Pixelshaderhighp = 'pixelshaderhighp';

	/**
	 * Whether shaders can use the dFdx, dFdy, and fwidth functions for computing derivatives.
	 */
	var Shaderderivatives = 'shaderderivatives';
}