// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.graphics;

/**
 * Vertex map datatype for Data variant of Mesh:setVertexMap.
 */
enum abstract IndexDataType (String) from String to String {

	/**
	 * The vertex map is array of unsigned word (16-bit).
	 */
	var Uint16 = 'uint16';

	/**
	 * The vertex map is array of unsigned dword (32-bit).
	 */
	var Uint32 = 'uint32';
}