// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.graphics;

/**
 * Line join style.
 */
enum abstract LineJoin (String) {

	/**
	 * The ends of the line segments beveled in an angle so that they join seamlessly.
	 */
	var Miter = 'miter';

	/**
	 * No cap applied to the ends of the line segments.
	 */
	var None = 'none';

	/**
	 * Flattens the point where line segments join together.
	 */
	var Bevel = 'bevel';
}