// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.graphics;

/**
 * The styles in which lines are drawn.
 */
enum abstract LineStyle (String) {

	/**
	 * Draw rough lines.
	 */
	var Rough = 'rough';

	/**
	 * Draw smooth lines.
	 */
	var Smooth = 'smooth';
}