// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.graphics;

/**
 * How a Mesh's vertices are used when drawing.
 */
enum abstract MeshDrawMode (String) from String to String {

	/**
	 * The vertices create a "fan" shape with the first vertex acting as the hub point. Can be easily used to draw simple convex polygons.
	 */
	var Fan = 'fan';

	/**
	 * The vertices create a series of connected triangles using vertices 1, 2, 3, then 3, 2, 4 (note the order), then 3, 4, 5, and so on.
	 */
	var Strip = 'strip';

	/**
	 * The vertices create unconnected triangles.
	 */
	var Triangles = 'triangles';

	/**
	 * The vertices are drawn as unconnected points (see love.graphics.setPointSize.)
	 */
	var Points = 'points';
}