// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.graphics;

/**
 * Controls whether a Canvas has mipmaps, and its behaviour when it does.
 */
enum abstract MipmapMode (String) {

	/**
	 * The Canvas has no mipmaps.
	 */
	var None = 'none';

	/**
	 * The Canvas has mipmaps. love.graphics.setCanvas can be used to render to a specific mipmap level, or Canvas:generateMipmaps can (re-)compute all mipmap levels based on the base level.
	 */
	var Auto = 'auto';

	/**
	 * The Canvas has mipmaps, and all mipmap levels will automatically be recomputed when switching away from the Canvas with love.graphics.setCanvas.
	 */
	var Manual = 'manual';
}