// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.graphics;

/**
 * How newly created particles are added to the ParticleSystem.
 */
enum abstract ParticleInsertMode (String) {

	/**
	 * Particles are inserted at the top of the ParticleSystem's list of particles.
	 */
	var Top = 'top';

	/**
	 * Particles are inserted at the bottom of the ParticleSystem's list of particles.
	 */
	var Bottom = 'bottom';

	/**
	 * Particles are inserted at random positions in the ParticleSystem's list of particles.
	 */
	var Random = 'random';
}