// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.graphics;
import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

/**
 * A quadrilateral (a polygon with four sides and four corners) with texture coordinate information.
 * Quads can be used to select part of a texture to draw. In this way, one large texture atlas can be loaded, and then split up into sub-images.
 */
extern class Quad extends Object {

	/**
	 * Gets reference texture dimensions initially specified in love.graphics.newQuad.
	 */
	public function getTextureDimensions(): QuadGetTextureDimensionsResult;

	/**
	 * Gets the current viewport of this Quad.
	 */
	public function getViewport(): QuadGetViewportResult;

	/**
	 * Sets the texture coordinates according to a viewport.
	 * @param x The top-left corner along the x-axis.
	 * @param y The top-left corner along the y-axis.
	 * @param w The width of the viewport.
	 * @param h The height of the viewport.
	 * @param sw Optional new reference width, the width of the Texture. Must be greater than 0 if set.
	 * @param sh Optional new reference height, the height of the Texture. Must be greater than 0 if set.
	 */
	public function setViewport(x: Float, y: Float, w: Float, h: Float, ?sw: Float, ?sh: Float): Void;
}

@:multiReturn
extern class QuadGetViewportResult {
	var x: Float;
	var y: Float;
	var w: Float;
	var h: Float;
}

@:multiReturn
extern class QuadGetTextureDimensionsResult {
	var sw: Float;
	var sh: Float;
}