// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.graphics;

/**
 * Usage hints for SpriteBatches and Meshes to optimize data storage and access.
 */
enum abstract SpriteBatchUsage (String) {

	/**
	 * The object's data will change occasionally during its lifetime. 
	 */
	var Dynamic = 'dynamic';

	/**
	 * The object will not be modified after initial sprites or vertices are added.
	 */
	var Static = 'static';

	/**
	 * The object data will always change between draws.
	 */
	var Stream = 'stream';
}