// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.graphics;

/**
 * Graphics state stack types used with love.graphics.push.
 */
enum abstract StackType (String) {

	/**
	 * The transformation stack (love.graphics.translate, love.graphics.rotate, etc.)
	 */
	var Transform = 'transform';

	/**
	 * All love.graphics state, including transform state.
	 */
	var All = 'all';
}