// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.graphics;

/**
 * How a stencil function modifies the stencil values of pixels it touches.
 */
enum abstract StencilAction (String) {

	/**
	 * The stencil value of a pixel will be replaced by the value specified in love.graphics.stencil, if any object touches the pixel.
	 */
	var Replace = 'replace';

	/**
	 * The stencil value of a pixel will be incremented by 1 for each object that touches the pixel. If the stencil value reaches 255 it will stay at 255.
	 */
	var Increment = 'increment';

	/**
	 * The stencil value of a pixel will be decremented by 1 for each object that touches the pixel. If the stencil value reaches 0 it will stay at 0.
	 */
	var Decrement = 'decrement';

	/**
	 * The stencil value of a pixel will be incremented by 1 for each object that touches the pixel. If a stencil value of 255 is incremented it will be set to 0.
	 */
	var Incrementwrap = 'incrementwrap';

	/**
	 * The stencil value of a pixel will be decremented by 1 for each object that touches the pixel. If the stencil value of 0 is decremented it will be set to 255.
	 */
	var Decrementwrap = 'decrementwrap';

	/**
	 * The stencil value of a pixel will be bitwise-inverted for each object that touches the pixel. If a stencil value of 0 is inverted it will become 255.
	 */
	var Invert = 'invert';
}