// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.graphics;

/**
 * Types of textures (2D, cubemap, etc.)
 */
enum abstract TextureType (String) {

	/**
	 * Regular 2D texture with width and height.
	 */
	var _2d = '2d';

	/**
	 * Several same-size 2D textures organized into a single object. Similar to a texture atlas / sprite sheet, but avoids sprite bleeding and other issues.
	 */
	var Array = 'array';

	/**
	 * Cubemap texture with 6 faces. Requires a custom shader (and Shader:send) to use. Sampling from a cube texture in a shader takes a 3D direction vector instead of a texture coordinate.
	 */
	var Cube = 'cube';

	/**
	 * 3D texture with width, height, and depth. Requires a custom shader to use. Volume textures can have texture filtering applied along the 3rd axis.
	 */
	var Volume = 'volume';
}