// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.graphics;

/**
 * How Mesh geometry vertices are ordered.
 */
enum abstract VertexWinding (String) {

	/**
	 * Clockwise.
	 */
	var Cw = 'cw';

	/**
	 * Counter-clockwise.
	 */
	var Ccw = 'ccw';
}