// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.window;

/**
 * Types of device display orientation.
 */
enum abstract DisplayOrientation (String) {

	/**
	 * Orientation cannot be determined.
	 */
	var Unknown = 'unknown';

	/**
	 * Landscape orientation.
	 */
	var Landscape = 'landscape';

	/**
	 * Landscape orientation (flipped).
	 */
	var Landscapeflipped = 'landscapeflipped';

	/**
	 * Portrait orientation.
	 */
	var Portrait = 'portrait';

	/**
	 * Portrait orientation (flipped).
	 */
	var Portraitflipped = 'portraitflipped';
}