// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.window;

/**
 * Types of message box dialogs. Different types may have slightly different looks.
 */
enum abstract MessageBoxType (String) {

	/**
	 * Informational dialog.
	 */
	var Info = 'info';

	/**
	 * Warning dialog.
	 */
	var Warning = 'warning';

	/**
	 * Error dialog.
	 */
	var Error = 'error';
}