// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.filesystem;

/**
 * Buffer modes for File objects.
 */
enum abstract BufferMode (String) {

	/**
	 * No buffering. The result of write and append operations appears immediately.
	 */
	var None = 'none';

	/**
	 * Line buffering. Write and append operations are buffered until a newline is output or the buffer size limit is reached.
	 */
	var Line = 'line';

	/**
	 * Full buffering. Write and append operations are always buffered until the buffer size limit is reached.
	 */
	var Full = 'full';
}