// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.filesystem;
import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

/**
 * Represents a file dropped onto the window.
 * Note that the DroppedFile type can only be obtained from love.filedropped callback, and can't be constructed manually by the user.
 */
extern class DroppedFile extends File {
}