// Generated by https://github.com/square-two/love2d-hx.
// Love2D Version 11.5.

package love.filesystem;
import haxe.extern.Rest;
import lua.Table;
import lua.UserData;

/**
 * Data representing the contents of a file.
 */
extern class FileData extends Data {

	/**
	 * Gets the extension of the FileData.
	 * @return The extension of the file the FileData represents.
	 */
	public function getExtension(): String;

	/**
	 * Gets the filename of the FileData.
	 * @return The name of the file the FileData represents.
	 */
	public function getFilename(): String;
}