// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.filesystem;

/**
 * The different modes you can open a File in.
 */
enum abstract FileMode (String) from String to String {

	/**
	 * Open a file for read.
	 */
	var R = 'r';

	/**
	 * Open a file for write.
	 */
	var W = 'w';

	/**
	 * Open a file for append.
	 */
	var A = 'a';

	/**
	 * Do not open a file (represents a closed file.)
	 */
	var C = 'c';
}