// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.filesystem;

/**
 * The type of a file.
 */
enum abstract FileType (String) {

	/**
	 * Regular file.
	 */
	var File = 'file';

	/**
	 * Directory.
	 */
	var Directory = 'directory';

	/**
	 * Symbolic link.
	 */
	var Symlink = 'symlink';

	/**
	 * Something completely different like a device.
	 */
	var Other = 'other';
}