// Generated by https://github.com/jurmerlo/love2d-hx.
// Love2D Version 11.5.

package love.filesystem;

/**
 * How to decode a given FileData.
 */
enum abstract FileDecoder (String) from String to String {

	/**
	 * The data is unencoded.
	 */
	var File = 'file';

	/**
	 * The data is base64-encoded.
	 */
	var Base64 = 'base64';
}